/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-19 15:20:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import techcraft.admin.model.Student;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import techcraft.admin.model.Student;
import java.util.List;

public final class addStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("techcraft.admin.model.Student");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("org.hibernate.cfg.Configuration");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"adminIndex.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        <script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    	.progress-bar {\r\n");
      out.write("		    width: 20px;\r\n");
      out.write("		    height: 20px;\r\n");
      out.write("		    margin-right: 20px; \r\n");
      out.write("		    margin-left: 20px;\r\n");
      out.write("		    border-radius: 50%;\r\n");
      out.write("		    border: 4px solid black;\r\n");
      out.write("		    border-top-color: #ffa200;\r\n");
      out.write("		    animation: spin 1s linear infinite;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.hidden {\r\n");
      out.write("		    display: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes spin {\r\n");
      out.write("		    0% { transform: rotate(0deg); }\r\n");
      out.write("		    100% { transform: rotate(360deg); }\r\n");
      out.write("		}\r\n");
      out.write("    	\r\n");
      out.write("    	.dashboard-heading {\r\n");
      out.write("			margin: 10px 20px;\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.dashboard-heading span {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.about {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			flex-direction: column;\r\n");
      out.write("			flex: 1;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main {\r\n");
      out.write("			width: auto;\r\n");
      out.write("		    height: auto;\r\n");
      out.write("		    padding: 0px 30px;\r\n");
      out.write("		    border-radius: 20px;\r\n");
      out.write("		    background-size: cover; \r\n");
      out.write("		    border: 2px solid #000; \r\n");
      out.write("		    background-image: url(\"./media/techback.jpg\"); \r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("		@keyframes zoomInOut {\r\n");
      out.write("		    0% {\r\n");
      out.write("		        transform: scale(1);\r\n");
      out.write("		    }\r\n");
      out.write("		    100% {\r\n");
      out.write("		        transform: scale(1.1);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.roadmap-main p {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			margin: 0px 100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main fieldset {\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        margin: 10px 50px;\r\n");
      out.write("	        margin-bottom: 50px;\r\n");
      out.write("	        background-color: #fff;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        border: solid 4px #00bfff;\r\n");
      out.write("	        border-radius: 20px;\r\n");
      out.write("	        height: auto; \r\n");
      out.write("	        padding-right: 30px;\r\n");
      out.write("	        padding-top: 0px;\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("		legend {\r\n");
      out.write("			background-color: #ffa200;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("			padding: 15px;\r\n");
      out.write("			font-size: 13px;\r\n");
      out.write("		}\r\n");
      out.write("		  \r\n");
      out.write("		.socialMedia img {\r\n");
      out.write("		    width: 10%;\r\n");
      out.write("		    height: 10%;\r\n");
      out.write("		    margin-left: 15px;\r\n");
      out.write("		    cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.pre-footer {\r\n");
      out.write("			display: flex; \r\n");
      out.write("			align-items: center; \r\n");
      out.write("			justify-content: center; \r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.pre-footer button {\r\n");
      out.write("			color: #002233;\r\n");
      out.write("		    cursor: pointer;\r\n");
      out.write("		    font-weight: bold;\r\n");
      out.write("		    background-color: #ffa200;\r\n");
      out.write("		    letter-spacing: 1px;\r\n");
      out.write("		    border: none;\r\n");
      out.write("		    padding: 15px 30px;\r\n");
      out.write("		    margin: 10px;\r\n");
      out.write("		    margin-left: 40px;\r\n");
      out.write("		    border-radius: 15px;\r\n");
      out.write("		    font-size: large;\r\n");
      out.write("		    animation: zoomInOut 0.5s infinite alternate;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.footer-content h4{\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			padding-bottom: 20px;\r\n");
      out.write("			border-bottom: solid 2px #fff;\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.footer-content div{  \r\n");
      out.write("			font-size: 13px; \r\n");
      out.write("			max-width: 400px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			color: white;\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.footer-content a{  \r\n");
      out.write("			color: white;\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.footer-content a:hover{  \r\n");
      out.write("			color: #ffa200; \r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.footer-social-media img{   \r\n");
      out.write("			color: white;\r\n");
      out.write("			width: 30px;\r\n");
      out.write("			height: 30px; \r\n");
      out.write("			padding: 5px; \r\n");
      out.write("			cursor: pointer; \r\n");
      out.write("			border: solid 2px #002233;\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.footer-social-media img:hover{   \r\n");
      out.write("			border: solid 2px #ffa200;\r\n");
      out.write("			padding: 5px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-student {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-student img {\r\n");
      out.write("			width: 700px;\r\n");
      out.write("			height: 700px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-form {\r\n");
      out.write("			margin: 20px;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-form input {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("	        padding: 15px;\r\n");
      out.write("	        margin: 5px 0px;\r\n");
      out.write("	        border-radius: 5px;\r\n");
      out.write("	        box-sizing: border-box;\r\n");
      out.write("	        border: 2px solid #000;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-form input:hover {\r\n");
      out.write("	    	transform: scale(1.02);\r\n");
      out.write("	    	border: 2px solid #0bbfff;\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("		.add-form button {\r\n");
      out.write("			color: #fff;\r\n");
      out.write("	        cursor: pointer;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        background-color: #00334d;\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        border: none;\r\n");
      out.write("	        padding: 15px 50px;\r\n");
      out.write("	        margin-left: 20px;\r\n");
      out.write("	        border-radius: 10px;\r\n");
      out.write("	        font-size: 15px; \r\n");
      out.write("	        transition: transform 0.3s ease; \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.add-form button:hover {\r\n");
      out.write("	    	transform: scale(1.1);\r\n");
      out.write("	    }\r\n");
      out.write("				\r\n");
      out.write("    </style>\r\n");
      out.write("     \r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    	");

	        String name = (String) session.getAttribute("name");
	        if (name == null) {
	            response.sendRedirect("index.jsp");
	        } else {
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	    ");
 
	        String status = (String)request.getAttribute("status");
	        if (status != null && status.equals("Success")) {
	    
      out.write("\r\n");
      out.write("	            <script type=\"text/javascript\">\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		            	title: \"Congrates !\",\r\n");
      out.write("		            	text: \"Student added Successfully !\",\r\n");
      out.write("		            	icon: \"success\",\r\n");
      out.write("		            	showConfirmButton: false,\r\n");
      out.write("		            	timer: 2500,\r\n");
      out.write("	            	});\r\n");
      out.write("	            </script>\r\n");
      out.write("	    ");

	        }
	        if (status != null && status.equals("failed")) {
	    
      out.write("\r\n");
      out.write("	    	            <script type=\"text/javascript\">\r\n");
      out.write("	    		            Swal.fire({\r\n");
      out.write("	    		            	title: \"Email already Exist !\",\r\n");
      out.write("	    		            	text: \"Please select different email !\",\r\n");
      out.write("	    		            	icon: \"error\",\r\n");
      out.write("	    		            	showConfirmButton: false,\r\n");
      out.write("	    		            	timer: 3000,\r\n");
      out.write("	    	            	});\r\n");
      out.write("	    	            </script>\r\n");
      out.write("	    ");

	        } 
	    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"adminHome.jsp\" style=\"margin-top: 10px;\">Student Details</a>\r\n");
      out.write("                <a href=\"addStudent.jsp\" style=\"border-bottom: 2px solid #ffa200; margin-top: 10px; padding-bottom: 10px;\">Add Student</a>\r\n");
      out.write("                <a href=\"addTeacher.jsp\" style=\"margin-top: 10px;  \">Add Teacher</a>\r\n");
      out.write("                <a href=\"viewFeedbacks.jsp\" style=\"margin-top: 10px; \">View Feedback</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1; margin-right: 0px;\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 15px\">\r\n");
      out.write("        	<div class=\"popup\">\r\n");
      out.write("			  <label for=\"user\" class=\"userName\">");
      out.print( name );
      out.write("<img class=\"dropdown-icon\" alt=\"\" src=\"./media/play.png\"></label>    \r\n");
      out.write("			  <div class=\"popup-content\">  \r\n");
      out.write("			    <a href=\"#\">Profile</a> \r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"#\" onclick=\"openModal('logoutModal')\">Logout</a>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div> \r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard-heading\">\r\n");
      out.write("        	<span style=\"font-size: 15px; color: #888888\">Dashboard:</span>\r\n");
      out.write("        	<span style=\"color: white\"> Add Student</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"roadmap-main\">\r\n");
      out.write("        	<div class=\"roadmap-heading\"> <br>\r\n");
      out.write("        		<p>Register a new student to the TechCraft Learning Hub by entering their details, ensuring they can access and benefit from our comprehensive learning resources and track their progress within the platform :</p> <br>\r\n");
      out.write("        		<fieldset>\r\n");
      out.write("		            <legend style=\"color: white; font-weight: bold;\">Add Student</legend> \r\n");
      out.write("		            <div class=\"add-student\">\r\n");
      out.write("		            	<img src=\"./media/freelancer.svg\"> \r\n");
      out.write("		                <div class=\"add-form\">\r\n");
      out.write("			                <h2 style=\"text-align: center; color: black\">Add Student</h2>\r\n");
      out.write("			                <form id=\"register-user\" action=\"AddStudent\" method=\"post\">\r\n");
      out.write("		                	<div style=\"display: flex; margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/black-user.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"text\" id=\"firstName\" name=\"firstName\" placeholder=\"First Name\" required><br>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div style=\"display: flex;margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/black-user.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"text\" id=\"lastName\" name=\"lastName\" placeholder=\"Last Name\" required><br>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div style=\"display: flex;margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div style=\"display: flex;margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/mobile.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"text\" id=\"number\" name=\"number\" placeholder=\"Mobile No\" required><br>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div style=\"display: flex;margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/lock.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\" required><br>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div style=\"display: flex;margin-bottom: 20px\">\r\n");
      out.write("		                		<img src=\"./media/confirm.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 15px;\">\r\n");
      out.write("		                		<input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm Password\" required><br>\r\n");
      out.write("		                	</div> \r\n");
      out.write("						    <div style=\"display: flex; align-items: center; text-align: center; margin-left: 35px\">\r\n");
      out.write("							    <div class=\"register-container\">\r\n");
      out.write("							    	<input type=\"button\" class=\"register\" value=\"add student\" id=\"signUpButton\" onclick=\"registerClicked('registrationModal')\" style=\"background-color: #ffa200; cursor: pointer;\">\r\n");
      out.write("							    	<div class=\"progress-bar hidden\" id=\"proBar\"></div>\r\n");
      out.write("							    </div>\r\n");
      out.write("							    <p id=\"error\" style=\"font-size: 10px; color: red; margin-left: 20px;\"></p>\r\n");
      out.write("						    </div> \r\n");
      out.write("						</form>\r\n");
      out.write("		            	</div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </fieldset>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div id=\"logoutModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal content -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"max-width: 300px; margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);\">\r\n");
      out.write("                <form id=\"logoutForm\" action=\"AdminLogout\">\r\n");
      out.write("                    <p style=\"color: black\">Are you sure, you want to Logout ?</p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px; align-item: center\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #ffa200; border: none\" value=\"Yes\"\r\n");
      out.write("                            onclick=\"logOut()\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #d2d2e0; border: none\" value=\"Cancel\"\r\n");
      out.write("                            onclick=\"closeModal('logoutModal')\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function openModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	        }\r\n");
      out.write("	\r\n");
      out.write("	        function closeModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'none';\r\n");
      out.write("	        }  \r\n");
      out.write("	        \r\n");
      out.write("	        function logOut() {\r\n");
      out.write("                document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\"> \r\n");
      out.write("        \r\n");
      out.write("        	function registerClicked(modalId) { \r\n");
      out.write("	        	if (validateForm()) {\r\n");
      out.write("	        		document.getElementById(\"signUpButton\").style.display = \"none\"; \r\n");
      out.write("		            document.getElementById(\"proBar\").classList.remove(\"hidden\");\r\n");
      out.write("		            setTimeout(function() {\r\n");
      out.write("		            	document.getElementById(\"register-user\").submit(); \r\n");
      out.write("		            }, 500); \r\n");
      out.write("		        } \r\n");
      out.write("	        }\r\n");
      out.write("         \r\n");
      out.write("		    function validateForm() {\r\n");
      out.write("		        var firstName = document.getElementById(\"firstName\");\r\n");
      out.write("		        var lastName = document.getElementById(\"lastName\");\r\n");
      out.write("		        var email = document.getElementById(\"email\");\r\n");
      out.write("		        var number = document.getElementById(\"number\");\r\n");
      out.write("		        var password = document.getElementById(\"password\");\r\n");
      out.write("		        var confirmPassword = document.getElementById(\"confirmPassword\");\r\n");
      out.write("		\r\n");
      out.write("		        var valid = true;\r\n");
      out.write("		 \r\n");
      out.write("		        var nameRegex = /^[a-zA-Z]+$/;  \r\n");
      out.write("		        var emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("		        var passwordRegex = /^(?=.*[A-Z])(?=.*\\d).{6,}$/;  \r\n");
      out.write("		        var mobileRegex = /^[6-9]\\d{9}$/;  \r\n");
      out.write("		        \r\n");
      out.write("		        var error = document.getElementById(\"error\");\r\n");
      out.write("		        error.innerHTML = \"\"; \r\n");
      out.write("		\r\n");
      out.write("		      \r\n");
      out.write("		        if (!nameRegex.test(firstName.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid first name (only letters).\";\r\n");
      out.write("		            firstName.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid; \r\n");
      out.write("		        } else {\r\n");
      out.write("		            firstName.style.border = \"\"; \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        if (!nameRegex.test(lastName.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid last name (only letters).\";\r\n");
      out.write("		            lastName.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            lastName.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        if (!emailRegex.test(email.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid email address.\";\r\n");
      out.write("		            email.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            email.style.border = \"\"; \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (!mobileRegex.test(number.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid 10-digit mobile number starting with 6, 7, 8, or 9.\";\r\n");
      out.write("		            number.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            number.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (!passwordRegex.test(password.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Password must be at least 6 characters long, have at least one uppercase letter, and one number.\";\r\n");
      out.write("		            password.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            password.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (confirmPassword.value.trim() !== password.value.trim()) {\r\n");
      out.write("		            error.innerHTML = \"Confirm Password and Passwords do not match.\";\r\n");
      out.write("		            confirmPassword.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid; \r\n");
      out.write("		        } else {\r\n");
      out.write("		            confirmPassword.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        return valid;\r\n");
      out.write("		    }\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("        <footer style=\"background-color: #002233; display: flex; justify-content: space-between; margin: 0px 50px; color: #ffa200;\">\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>About Us</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<p>Technolearn Trainings is one of the best training institutes in Sinhagad Road/Anand Nagar, Pune. We provide professional courses for students, working professionals, job seekers and corporate employees with placement assurance.</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Features</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<a href=\"teacherHome.jsp\">Technology Roadmaps</a><p></p>\r\n");
      out.write("	                <a href=\"videoLecture.jsp\">Video Lectures</a><p></p>\r\n");
      out.write("	                <a href=\"codingEnhancement.jsp\">Coding Enhancement</a><p></p>\r\n");
      out.write("	                <a href=\"technicalQuiz.jsp\">Technical Quiz</a><p></p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Contact </h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<div style=\"margin-top: 20px;\">\r\n");
      out.write("                    <img src=\"./media/pin.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("                    <span id=\"tick-text\">Technolearn Trainings 133, Peshwa, 2nd Floor, Office No. 09, Near Chaitanya Hospital, Next to Parvati Bridge, Sinhgad Road, Parvati, Pune - 411030.</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/phone.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">91 88570 96492</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/email (1).png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">Info.technolearn@gmail.com</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Follow Us</h4>\r\n");
      out.write("        		<div class=\"footer-social-media\">\r\n");
      out.write("        			<a href=\"#\"><img src=\"./media/twitter.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/facebook.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/linkedin.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/instagram.png\"></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
