/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-19 08:47:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"adminIndex.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        <script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    	.progress-bar {\r\n");
      out.write("		    width: 20px;\r\n");
      out.write("		    height: 20px;\r\n");
      out.write("		    margin-right: 20px; \r\n");
      out.write("		    margin-left: 20px;\r\n");
      out.write("		    border-radius: 50%;\r\n");
      out.write("		    border: 4px solid black;\r\n");
      out.write("		    border-top-color: #ffa200;\r\n");
      out.write("		    animation: spin 1s linear infinite;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.hidden {\r\n");
      out.write("		    display: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes spin {\r\n");
      out.write("		    0% { transform: rotate(0deg); }\r\n");
      out.write("		    100% { transform: rotate(360deg); }\r\n");
      out.write("		}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("		\r\n");
      out.write("    <body>\r\n");
      out.write("    	\r\n");
      out.write("    	");
 
	        String status = (String)request.getAttribute("status");
	        if (status != null && status.equals("Success")) {
	    
      out.write("\r\n");
      out.write("	            <script type=\"text/javascript\">\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		            	title: \"Congrates !\",\r\n");
      out.write("		            	text: \"Acount Created Successfully !\",\r\n");
      out.write("		            	icon: \"success\",\r\n");
      out.write("		            	showConfirmButton: false,\r\n");
      out.write("		            	timer: 2500,\r\n");
      out.write("	            	});\r\n");
      out.write("	            </script>\r\n");
      out.write("	    ");

	        }
	        if (status != null && status.equals("error")) {
	    
      out.write("\r\n");
      out.write("	    		<script type=\"text/javascript\">\r\n");
      out.write("	    		            Swal.fire({\r\n");
      out.write("	    		            	title: \"Sign In Failed !\",\r\n");
      out.write("	    		            	text: \"Wrong Email or Password !\",\r\n");
      out.write("	    		            	icon: \"error\",\r\n");
      out.write("	    		            	showConfirmButton: false,\r\n");
      out.write("	    		            	timer: 2500,\r\n");
      out.write("	    	            	});\r\n");
      out.write("	    	    </script>\r\n");
      out.write("	     ");

	    	}
	        if (status != null && status.equals("found")) {
	   	 
      out.write("\r\n");
      out.write("	   	    	    		<script type=\"text/javascript\">\r\n");
      out.write("	   	    	    		            Swal.fire({\r\n");
      out.write("	   	    	    		            	title: \"Check Email !\",\r\n");
      out.write("	   	    	    		            	text: \"Your credentials have been sent to the registered email address!\",\r\n");
      out.write("	   	    	    		            	icon: \"success\",\r\n");
      out.write("	   	    	    		            	showConfirmButton: false,\r\n");
      out.write("	   	    	    		            	timer: 3000,\r\n");
      out.write("	   	    	    	            	});\r\n");
      out.write("	   	    	    	    </script>\r\n");
      out.write("	   	    ");

	   	    	}
	   	        if (status != null && status.equals("notFound")) {
	   	    
      out.write("\r\n");
      out.write("	   	    	    		<script type=\"text/javascript\">\r\n");
      out.write("	   	    	    		            Swal.fire({\r\n");
      out.write("	   	    	    		            	title: \"Email not registed !\",\r\n");
      out.write("	   	    	    		            	text: \"Please Register to TechCraft !\",\r\n");
      out.write("	   	    	    		            	icon: \"error\",\r\n");
      out.write("	   	    	    		            	showConfirmButton: false,\r\n");
      out.write("	   	    	    		            	timer: 2500,\r\n");
      out.write("	   	    	    	            	});\r\n");
      out.write("	   	    	    	    </script>\r\n");
      out.write("	   	    ");

	   	   		}
	   	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"index.jsp\">Home</a>\r\n");
      out.write("                <a onclick=\"openModal('AboutModel')\">About</a>\r\n");
      out.write("                <a href=\"#\">Contact</a>\r\n");
      out.write("                <a href=\"#\">Feedback</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 20px\">\r\n");
      out.write("            <span>Administrator</span>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <img src=\"./media/remote-team.svg\">\r\n");
      out.write("            <div class=\"about\">\r\n");
      out.write("                <h1>Welcome to TechCraft</h1>\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("	                <h2 style=\"text-align: center; color: black\">Administrator Sign In</h2>\r\n");
      out.write("	                <form id=\"login-user\" action=\"AdminLogin\" method=\"post\">\r\n");
      out.write("	                	<div style=\"display: flex;\">\r\n");
      out.write("	                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("	                		<input id=\"loginEmail\" type=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("	                	</div>\r\n");
      out.write("	                	<div style=\"display: flex;\">\r\n");
      out.write("	                		<img src=\"./media/lock.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("	                		<input id=\"loginPass\" type=\"password\" name=\"password\" placeholder=\"Password\" required><br>\r\n");
      out.write("	                	</div>\r\n");
      out.write("	                    \r\n");
      out.write("	                    <div style=\"display: flex; margin-left: 35px\">\r\n");
      out.write("	                        <div class=\"login-container\">\r\n");
      out.write("							  <input type=\"button\" class=\"login\" value=\"Sign In\" id=\"signInButton\" onclick=\"loginClicked()\" style=\"background-color: #ffa200\">\r\n");
      out.write("							  <div class=\"progress-bar hidden\" id=\"progressBar\"></div>\r\n");
      out.write("							</div> \r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <hr>\r\n");
      out.write("	                    <a class=\"clickLogin\" style=\"font-size: small; text-align: center;\" onclick=\"openModal('forgotPassword')\">Forgot Password ?</a>\r\n");
      out.write("	                </form>\r\n");
      out.write("            	</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button onclick=\"scrollToTop()\" id=\"scrollBtn\" title=\"Go to top\"><img class=\"go-top\" alt=\"\" src=\"./media/play.png\"></button>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"AboutModel\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal about -->\r\n");
      out.write("            <div class=\"site-content\">\r\n");
      out.write("                <div style=\"padding: 20px; display: flex; border-radius: 10px\">\r\n");
      out.write("                    <img src=\"./media/success.svg\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span style=\"color: black\" onclick=\"closeModal('AboutModel')\" class=\"close\">&times;</span>\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #ffa200; animation: zoomInOut 0.5s infinite alternate;\">\r\n");
      out.write("                            About TechCraft</h2>\r\n");
      out.write("                        <p>TechCraft Learning Hub is an online learning platform that helps you to\r\n");
      out.write("                            learn and develop your skills.</p>\r\n");
      out.write("                        <p>Mission Statement:</p>\r\n");
      out.write("                        <div class=\"sub-about\">At TechCraft Learning Platform, our mission is to democratize access to\r\n");
      out.write("                            quality tech education and empower learners worldwide to achieve their professional goals.\r\n");
      out.write("                            We believe that by providing comprehensive learning resources and fostering a supportive\r\n");
      out.write("                            learning community, we can inspire individuals to pursue their passion for technology and\r\n");
      out.write("                            thrive in today's digital landscape.</div>\r\n");
      out.write("                        <p>Join Us Today:</p>\r\n");
      out.write("                        <div class=\"sub-about\">Embark on your learning journey with TechCraft Learning Platform and\r\n");
      out.write("                            unlock your full potential in the world of technology. Whether you're a student, a working\r\n");
      out.write("                            professional, or a tech enthusiast, our platform offers something for everyone. Join our\r\n");
      out.write("                            vibrant community of learners today and take the first step towards a successful tech\r\n");
      out.write("                            career! make it spell correct</div>\r\n");
      out.write("                        <p style=\"color: #ffa200; animation: zoomInOut 0.5s infinite alternate;\">All The Best !</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"forgotPassword\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal Login -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);\">\r\n");
      out.write("                <span style=\"color: black\" onclick=\"closeModal('forgotPassword')\" class=\"close\">&times;</span>\r\n");
      out.write("                <h2 style=\"text-align: center; color: black\">Forgot Password</h2>\r\n");
      out.write("                <form id=\"forgot-password\" action=\"AdminForgotPssword\" method=\"post\">\r\n");
      out.write("                	<p style=\"margin: 10px\">Enter your registered email :</p>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input id=\"forgotEmail\" type=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<hr>\r\n");
      out.write("                    <div class=\"login-container\">\r\n");
      out.write("						  <input type=\"button\" class=\"login\" value=\"Get Credentials\" id=\"getCredential\" onclick=\"getCredentialClicked()\" style=\"margin-top: 10px; background-color: #ffa200\">\r\n");
      out.write("						  <div class=\"progress-bar hidden\" id=\"forgotProgress\"></div>\r\n");
      out.write("					</div> \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("            function openModal(modalId) {\r\n");
      out.write("                var modal = document.getElementById(modalId);\r\n");
      out.write("                modal.style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function closeModal(modalId) {\r\n");
      out.write("                var modal = document.getElementById(modalId);\r\n");
      out.write("                modal.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("	        function loginClicked() { \r\n");
      out.write("	        	var loginEmail = document.getElementById(\"loginEmail\");\r\n");
      out.write("	        	var loginPass = document.getElementById(\"loginPass\");\r\n");
      out.write("	        	\r\n");
      out.write("	        	 if (loginEmail.value.trim().length === 0) {\r\n");
      out.write("	                 loginEmail.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	        	 else {\r\n");
      out.write("	        		 loginEmail.style.border = \"\"; // Reset border\r\n");
      out.write("			     }\r\n");
      out.write("	             if (loginPass.value.trim().length === 0) {\r\n");
      out.write("	                 loginPass.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	             else {\r\n");
      out.write("	            	 loginPass.style.border = \"\"; // Reset border\r\n");
      out.write("			     }\r\n");
      out.write("	            document.getElementById(\"signInButton\").style.display = \"none\"; \r\n");
      out.write("	            document.getElementById(\"progressBar\").classList.remove(\"hidden\"); \r\n");
      out.write("	            setTimeout(function() { \r\n");
      out.write("	            	document.getElementById(\"login-user\").submit();\r\n");
      out.write("	            }, 1500);  \r\n");
      out.write("	        }\r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("	        function getCredentialClicked() {\r\n");
      out.write("	        	var forgotEmail = document.getElementById(\"forgotEmail\"); \r\n");
      out.write("	        	\r\n");
      out.write("	        	 if (forgotEmail.value.trim().length === 0) {\r\n");
      out.write("	        		 forgotEmail.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	        	 else {\r\n");
      out.write("	        		 forgotEmail.style.border = \"\";  \r\n");
      out.write("			     }\r\n");
      out.write("	        	 document.getElementById(\"getCredential\").style.display = \"none\"; \r\n");
      out.write("		            document.getElementById(\"forgotProgress\").classList.remove(\"hidden\"); \r\n");
      out.write("		            setTimeout(function() { \r\n");
      out.write("		            	document.getElementById(\"forgot-password\").submit();\r\n");
      out.write("		            }, 1000);  \r\n");
      out.write("	        }\r\n");
      out.write("        </script>\r\n");
      out.write("         \r\n");
      out.write("		<script type=\"text/javascript\"> \r\n");
      out.write("		var mybutton = document.getElementById(\"scrollBtn\"); \r\n");
      out.write("		window.onscroll = function() {scrollFunction()};\r\n");
      out.write("\r\n");
      out.write("		function scrollFunction() {\r\n");
      out.write("		  if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {\r\n");
      out.write("		    mybutton.style.display = \"block\";\r\n");
      out.write("		  } else {\r\n");
      out.write("		    mybutton.style.display = \"none\";\r\n");
      out.write("		  }\r\n");
      out.write("		} \r\n");
      out.write("		function scrollToTop() { \r\n");
      out.write("		  document.documentElement.scrollTop = 0; \r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
