/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-17 09:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import techcraft.teacher.model.Assessment;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import techcraft.teacher.model.CodingAssessmentChallenge;
import techcraft.teacher.model.QuizAssessmentChallenge;
import java.util.List;

public final class generateAssessment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("techcraft.teacher.model.CodingAssessmentChallenge");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("techcraft.teacher.model.Assessment");
    _jspx_imports_classes.add("org.hibernate.cfg.Configuration");
    _jspx_imports_classes.add("techcraft.teacher.model.QuizAssessmentChallenge");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"teacherIndex.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        <script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    	.dashboard-heading {\r\n");
      out.write("			margin: 10px 20px;\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.dashboard-heading span {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("    	\r\n");
      out.write("    	.roadmap-main {\r\n");
      out.write("			width: auto;\r\n");
      out.write("		    height: auto;\r\n");
      out.write("		    background-size: cover; \r\n");
      out.write("		    border: 3px solid #000;\r\n");
      out.write("		    border-radius: 20px; \r\n");
      out.write("		    background-image: url(\"./media/techback.jpg\");\r\n");
      out.write("		    margin: 0px 20px;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("		@keyframes zoomInOut {\r\n");
      out.write("		    0% {\r\n");
      out.write("		        transform: scale(1);\r\n");
      out.write("		    }\r\n");
      out.write("		    100% {\r\n");
      out.write("		        transform: scale(1.05);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.roadmap-main p {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			margin: 0px 100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main h2 {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			animation: zoomInOut 0.5s infinite alternate;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main fieldset {\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        margin: 30px 50px;\r\n");
      out.write("	        background-color: #fff;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        border: solid 4px #00bfff;\r\n");
      out.write("	        border-radius: 20px;\r\n");
      out.write("	        height: auto; \r\n");
      out.write("	        padding-right: 30px;\r\n");
      out.write("	        padding-top: 0px;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    legend {\r\n");
      out.write("			background-color: #ffa200;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("			padding: 15px;\r\n");
      out.write("			font-size: 13px;\r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("		.student-details {\r\n");
      out.write("	        display: flex;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        align-items: center; \r\n");
      out.write("	    }\r\n");
      out.write("	     \r\n");
      out.write("		.add-challenge { \r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .add-challenge form {\r\n");
      out.write("	        margin: 20px;\r\n");
      out.write("	        padding: 20px;\r\n");
      out.write("	        margin-top: 0px;\r\n");
      out.write("	        padding-top: 10px;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .form-div {\r\n");
      out.write("	        font-size: 13px; \r\n");
      out.write("	        text-align: left;\r\n");
      out.write("	        margin: 10px; \r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .form-div label {\r\n");
      out.write("	        padding: 5px;\r\n");
      out.write("		    margin: 10px 0px;\r\n");
      out.write("		    width: auto;\r\n");
      out.write("		    white-space: nowrap;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .form-div input, .form-div option {\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        padding: 15px;\r\n");
      out.write("	        margin: 5px 0px;\r\n");
      out.write("	        border-radius: 5px;\r\n");
      out.write("	        box-sizing: border-box;\r\n");
      out.write("	        border: 2px solid #000;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        transition: transform 0.3s ease;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .form-div input:hover {\r\n");
      out.write("	    	transform: scale(1.02);\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .added-challenges {\r\n");
      out.write("	    	display: flex;\r\n");
      out.write("	    	margin: 25px 10px;\r\n");
      out.write("	    	padding: 15px;\r\n");
      out.write("	    	border: solid 2px #000;\r\n");
      out.write("	    	border-radius: 5px;\r\n");
      out.write("	    	margin-right: 0px;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .add-challenge button {\r\n");
      out.write("	        color: #fff;\r\n");
      out.write("	        cursor: pointer;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        background-color: #00334d;\r\n");
      out.write("	        letter-spacing: 1px;\r\n");
      out.write("	        border: none;\r\n");
      out.write("	        padding: 15px 50px;\r\n");
      out.write("	        margin-left: 20px;\r\n");
      out.write("	        border-radius: 10px;\r\n");
      out.write("	        font-size: 15px; \r\n");
      out.write("	        transition: transform 0.3s ease; \r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .add-challenge button:hover { \r\n");
      out.write("	        background-color: #00334d;\r\n");
      out.write("	        transform: scale(1.02);\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    table {\r\n");
      out.write("		    width: 100%;\r\n");
      out.write("		    border-collapse: collapse;\r\n");
      out.write("		    font-size: 13px;\r\n");
      out.write("		    background-color: #002233;\r\n");
      out.write("		    color: white;  \r\n");
      out.write("		    border-radius: 20px;\r\n");
      out.write("		    margin: 20px; \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		tr {\r\n");
      out.write("		    background-color: #fff;\r\n");
      out.write("		    color: black;  \r\n");
      out.write("		    margin: 10px; \r\n");
      out.write("		    text-align: center; \r\n");
      out.write("		    transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		tr:hover {\r\n");
      out.write("			transform: scale(1.01);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		td {  \r\n");
      out.write("		    border: none;\r\n");
      out.write("		    padding: 40px;  \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		th {\r\n");
      out.write("			background-color: #002233;\r\n");
      out.write("			color: #fff;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			padding: 10px; \r\n");
      out.write("			border: none; \r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("		.performance {\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("			color: #0bbfff;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("     \r\n");
      out.write("    </style>\r\n");
      out.write("     \r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    	");

	        String name = (String) session.getAttribute("name");
	        if (name == null) {
	            response.sendRedirect("index.jsp");
	        } else {
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	    ");
 
	    	String assessmentAdded = request.getParameter("status");
	    	if(assessmentAdded != null && assessmentAdded.equals("success")) { 
      out.write("\r\n");
      out.write("	    		<script type=\"text/javascript\">\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		            	title: \"Congrates !\",\r\n");
      out.write("		            	text: \"Assessment generated Successfully !\",\r\n");
      out.write("		            	icon: \"success\",\r\n");
      out.write("		            	showConfirmButton: false,\r\n");
      out.write("		            	timer: 2500,\r\n");
      out.write("	            	});\r\n");
      out.write("	        	</script> \r\n");
      out.write("		");
   
			}
	    
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"studentDetails.jsp\" style=\"margin-top: 10px;  \">Student Details</a>\r\n");
      out.write("                <a href=\"studentAttendance.jsp\" style=\"margin-top: 10px;\">Student Attendance</a>\r\n");
      out.write("                <a href=\"assessment.jsp\" style=\"border-bottom: 2px solid #ffa200; margin-top: 10px; padding-bottom: 10px;\">Technical Assessment</a>\r\n");
      out.write("                <a href=\"StudentProgress.jsp\" style=\"margin-top: 10px;\">Student's Progress</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1; margin-right: 0px;\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 15px\">\r\n");
      out.write("        	<div class=\"popup\">\r\n");
      out.write("			  <label for=\"user\" class=\"userName\">");
      out.print( name );
      out.write("<img class=\"dropdown-icon\" alt=\"\" src=\"./media/play.png\"></label>    \r\n");
      out.write("			  <div class=\"popup-content\">  \r\n");
      out.write("			    <a href=\"#\">Profile</a> \r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"studentFeedback.jsp\">Feedbacks</a>\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"#\" onclick=\"openModal('logoutModal')\">Logout</a>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div> \r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        ");
 String module = request.getParameter("module"); 
      out.write("\r\n");
      out.write("        <div class=\"dashboard-heading\">\r\n");
      out.write("        	<span style=\"font-size: 15px; color: #888888\">Dashboard:</span>\r\n");
      out.write("        	<span style=\"color: white\"> Technical Assessments</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"roadmap-main\">\r\n");
      out.write("        	<div class=\"roadmap-heading\"> \r\n");
      out.write("        		<h2> ");
      out.print( module );
      out.write(" Assessments</h2> \r\n");
      out.write("        		<p>Technical assessment of TechCraft Learning Hub is a platform to be a comprehensive resource with a wealth of learning opportunities. The interactive quizzes and coding challenges were particularly beneficial, allowing for hands-on learning.</p> \r\n");
      out.write("        		<fieldset>\r\n");
      out.write("		            <legend style=\"color: white; font-weight: bold;\">Generate Assessments</legend> \r\n");
      out.write("		            <div class=\"student-details\">\r\n");
      out.write("		            	");
 if(module.equals("Coding")) { 
      out.write("\r\n");
      out.write("							<img src=\"./media/software-engineer.svg\" alt=\"Illustration of a student\" width=\"500px\" height=\"500px\">\r\n");
      out.write("						");
 } else {
      out.write("\r\n");
      out.write("							<img src=\"./media/quiz.png\" alt=\"Illustration of a student\" width=\"450px\" height=\"400px\" style=\"margin-left: 20px;\">\r\n");
      out.write("						");
 } 
      out.write("   \r\n");
      out.write("				        <div class=\"add-challenge\">\r\n");
      out.write("				        \r\n");
      out.write("				        	");
	
				        		String topic = "";
					        	String instruction = "";
					        	String firstDate = "";
					        	String lastDate = "";
					        	String duration = "";
								
					        	if (request.getParameter("status") != null && request.getParameter("status").equals("added")) {
					                topic = request.getParameter("topic");
					                instruction = request.getParameter("instruction");
					                firstDate = request.getParameter("firstDate");
					                lastDate = request.getParameter("lastDate");
					                duration = request.getParameter("duration");
					            }
				        	
      out.write("\r\n");
      out.write("				        \r\n");
      out.write("				        	<form action=\"AddAssessment\" method=\"post\">\r\n");
      out.write("				        		<input type=\"hidden\" name=\"type\" value=\"");
      out.print( module );
      out.write("\">\r\n");
      out.write("				        		<input type=\"hidden\" name=\"instructor\" value=\"");
      out.print( name );
      out.write("\">\r\n");
      out.write("				        		<div class=\"form-div\" style=\"margin: 20px;\"> \r\n");
      out.write("				        			<label for=\"topic\">Topic:</label>\r\n");
      out.write("								    <input id=\"topic\" name=\"topic\" value=\"");
      out.print( topic );
      out.write("\" required></input>\r\n");
      out.write("								</div> \r\n");
      out.write("								<div class=\"form-div\" style=\"margin: 20px;\">\r\n");
      out.write("				                	<label for=\"Instruction\">Instruction:</label>\r\n");
      out.write("								    <input id=\"Instruction\" name=\"Instruction\" value=\"");
      out.print( instruction );
      out.write("\" required></input> \r\n");
      out.write("								</div> \r\n");
      out.write("								<div class=\"form-div\" style=\"display: flex; align-items: center; justify-content: space-between;\"> \r\n");
      out.write("									<div style=\"margin-left: 10px;\">\r\n");
      out.write("										<label for=\"assignedDate\">Assigned Date :</label>\r\n");
      out.write("								    	<input type=\"date\" id=\"assignedDate\" name=\"assignedDate\" value=\"");
      out.print( firstDate );
      out.write("\" required style=\"width: 200px\"  readonly=\"readonly\"></input>\r\n");
      out.write("								    </div>  \r\n");
      out.write("								    <script>\r\n");
      out.write("									    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("									        var today = new Date().toISOString().split('T')[0]; \r\n");
      out.write("									        document.getElementById(\"assignedDate\").value = today;\r\n");
      out.write("									    });\r\n");
      out.write("									</script>\r\n");
      out.write("								     \r\n");
      out.write("								    <div style=\"margin-left: 40px;\">\r\n");
      out.write("								    	<label for=\"lastDate\">Last Date :</label>\r\n");
      out.write("								    	<input type=\"date\" id=\"lastDate\" name=\"lastDate\" value=\"");
      out.print( lastDate );
      out.write("\" required style=\"width: 200px\"></input>\r\n");
      out.write("								    </div> \r\n");
      out.write("								    <div style=\"margin-left: 60px;\">\r\n");
      out.write("								    	<label for=\"duration\">Duration :</label>\r\n");
      out.write("								    	<input type=\"number\" id=\"duration\" name=\"duration\" value=\"");
      out.print( duration );
      out.write("\" required style=\"width: 200px\" placeholder=\"In Minutes\"></input>\r\n");
      out.write("								    </div> \r\n");
      out.write("								</div> \r\n");
      out.write("								<div class=\"form-div\">\r\n");
      out.write("									");
	  
					            		SessionFactory factory = new Configuration().configure().buildSessionFactory();
						            	Session studentSession = factory.openSession();
							        	try { 
							        		if(module.equals("Coding")) {
							        			Query<CodingAssessmentChallenge> query = studentSession.createQuery("FROM CodingAssessmentChallenge WHERE topic =:topic AND assignedDate =:assignedDate", CodingAssessmentChallenge.class);
							        			query.setParameter("topic", topic);
								            	query.setParameter("assignedDate", firstDate);
								            	List<CodingAssessmentChallenge> challenges = query.getResultList();
								
								                for (int i = 0; i < challenges.size(); i++) {
								                	CodingAssessmentChallenge challenge = challenges.get(i);
								    
      out.write("\r\n");
      out.write("								    				<div class=\"added-challenges\">\r\n");
      out.write("													<b>Challenge ");
      out.print( i+1 );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print( challenge.getChallengeTopic() );
      out.write("</b>\r\n");
      out.write("													<span style=\"flex: 1\"></span>\r\n");
      out.write("													<b style=\"font-size: 15px; cursor: pointer;\"> &times;</b>\r\n");
      out.write("													</div>\r\n");
      out.write("								    ");

								                }
								            }
							        		else {
							        			Query<QuizAssessmentChallenge> query = studentSession.createQuery("FROM QuizAssessmentChallenge WHERE topic =:topic AND assignedDate =:assignedDate", QuizAssessmentChallenge.class);
							        			query.setParameter("topic", topic);
								            	query.setParameter("assignedDate", firstDate);
								            	List<QuizAssessmentChallenge> challenges = query.getResultList();
								
								                for (int i = 0; i < challenges.size(); i++) {
								                	QuizAssessmentChallenge challenge = challenges.get(i);
								    
      out.write("\r\n");
      out.write("								    				<div class=\"added-challenges\">\r\n");
      out.write("													<b>Question ");
      out.print( i+1 );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print( challenge.getQuestion() );
      out.write("</b>\r\n");
      out.write("													<span style=\"flex: 1\"></span>\r\n");
      out.write("													<!--  <b style=\"font-size: 15px; cursor: pointer;\"> &times;</b> -->\r\n");
      out.write("													</div>\r\n");
      out.write("								    ");

								                }
							        		} 
							            } 
							            catch (Exception e) {  
							                e.printStackTrace();
							            } 
							            finally {
							                studentSession.close();
							                factory.close();
							            }
							        
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-div\" style=\"margin: 20px;\">\r\n");
      out.write("									");
 if(module.equals("Coding")) { 
      out.write("\r\n");
      out.write("								    	<button type=\"button\" onclick=\"openCodingModal()\" style=\"background-color: #0bbfff; border: none; color: #fff; width: auto; margin-left: 0px;\">Add Challenge +</button>\r\n");
      out.write("								    	<span style=\"font-size: 10px; margin-left: 10px;\">Note : You can add more challenges to this assessment later also, but only today !</span> \r\n");
      out.write("									");
 } else {
      out.write("\r\n");
      out.write("										<button type=\"button\" onclick=\"openCodingModal()\" style=\"background-color: #0bbfff; border: none; color: #fff; width: auto; margin-left: 0px;\">Add Question +</button>\r\n");
      out.write("										<span style=\"font-size: 10px; margin-left: 10px;\">Note : You can add more Questions to this assessment later also, but only today !</span> \r\n");
      out.write("									");
 } 
      out.write(" \r\n");
      out.write("								</div>  \r\n");
      out.write("								<button type=\"submit\" value=\"generate\" style=\"align-items: left; width: 100%; margin-left: 20px;\">Generate Assessment</button>\r\n");
      out.write("				            </form>\r\n");
      out.write("				        </div>\r\n");
      out.write("				    </div> \r\n");
      out.write("		        </fieldset>\r\n");
      out.write("		        <fieldset style=\"background-color: #002233; border: 4px solid #000; padding-right: 10px;\">\r\n");
      out.write("		            <legend style=\"color: white; font-weight: bold;\">Previous Assessments</legend> \r\n");
      out.write("		            <div class=\"student-details\">  \r\n");
      out.write("				        	<table>\r\n");
      out.write("				        		<tr>\r\n");
      out.write("				        			<th>Sr No.</th>\r\n");
      out.write("				        			<th>Topic</th>\r\n");
      out.write("				        			<th>Instructor</th>\r\n");
      out.write("				        			<th>Assigned Date</th>\r\n");
      out.write("				        			<th>Last Date</th>\r\n");
      out.write("				        			<th>Performance</th>\r\n");
      out.write("				        			<th></th> \r\n");
      out.write("				        		</tr> \r\n");
      out.write("				                 \r\n");
      out.write("				        		");
  
						            SessionFactory factory1 = new Configuration().configure().buildSessionFactory();
						            Session studentSession1 = factory1.openSession(); 
						            
						            try { 
						                Query<Assessment> query1 = studentSession1.createQuery("FROM Assessment WHERE type =:type AND instructor =:instructor", Assessment.class);
						                query1.setParameter("type", module);
						                query1.setParameter("instructor", name);
						                List<Assessment> assessments = query1.getResultList();
						
						                for (int i = 0; i < assessments.size(); i++) {
						                	Assessment assessment = assessments.get(i);
						        
      out.write("\r\n");
      out.write("									        <tr style=\"background-color: #002233; height: 8px\"></tr>\r\n");
      out.write("									        <tr>\r\n");
      out.write("									            <td style=\"border-bottom-left-radius: 10px; border-top-left-radius: 10px;\">");
      out.print( i + 1 );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( assessment.getTopic() );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( assessment.getInstructor() );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( assessment.getAssignedDate() );
      out.write("</td> \r\n");
      out.write("									            <td>");
      out.print( assessment.getLastDate() );
      out.write("<img src=\"./media/edit-text.png\" title=\"Change Date\" width=\"15px\" height=\"15px\" onclick=\"openModal('changeLastDate')\" style=\"margin-left: 10px; cursor: pointer;\"></td>\r\n");
      out.write("									            <td><a class=\"performance\" href=\"#\">View Performance</a></td> \r\n");
      out.write("									            <td style=\"border-bottom-right-radius: 10px; border-top-right-radius: 10px;\"><img src=\"./media/trash-bin.png\" title=\"Delete Assessment\" width=\"20px\" height=\"20px\" onclick=\"openModal('deleteAssessment')\" style=\"cursor: pointer;\"></td>\r\n");
      out.write("									        </tr> \r\n");
      out.write("						        ");
 
						                } 
						            } 
						            catch (Exception e) {  
						                e.printStackTrace();
						            } 
						            finally {
						                studentSession1.close();
						                factory1.close();
						            }
						        
      out.write("\r\n");
      out.write("						        <tr style=\"background-color: #002233; height: 8px\"></tr>\r\n");
      out.write("						        <tr> \r\n");
      out.write("									<td colspan=\"7\" style=\"border-radius: 10px;\">No more Records !</td> \r\n");
      out.write("								</tr>\r\n");
      out.write("				        	</table> \r\n");
      out.write("				    </div>\r\n");
      out.write("		        </fieldset> \r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"addChallenge\" class=\"modal-container\">\r\n");
      out.write("		    <!-- Modal Login -->\r\n");
      out.write("		    <div class=\"modal-content\" style=\"max-width: 1000px; margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); font-weight: bold;\">\r\n");
      out.write("		        <span style=\"color: black\" onclick=\"closeModal('addChallenge')\" class=\"close\">&times;</span>\r\n");
      out.write("		        ");
 if(module.equals("Coding")) { 
      out.write("\r\n");
      out.write("					<h2 style=\"text-align: center; color: black\">Add Challenge</h2>\r\n");
      out.write("				");
 } else {
      out.write("\r\n");
      out.write("					<h2 style=\"text-align: center; color: black\">Add Question</h2> \r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"add-challenge\">\r\n");
      out.write("		        	");
 if(module.equals("Coding")) { 
      out.write("\r\n");
      out.write("			            <form action=\"AddCodingChallenge\" method=\"post\" style=\"margin: 0px; padding: 0px;\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentTopic\" name=\"CodingAssessmentTopic\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentInstruction\" name=\"CodingAssessmentInstruction\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentDate\" name=\"CodingAssessmentDate\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentLastDate\" name=\"CodingAssessmentLastDate\"> \r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentDuration\" name=\"CodingAssessmentDuration\">\r\n");
      out.write("			            	\r\n");
      out.write("			            	<div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("				                <div class=\"form-div\"> \r\n");
      out.write("				                    <label for=\"CodingchallengeTopic\">Title:</label>\r\n");
      out.write("				                    <input id=\"CodingchallengeTopic\" name=\"CodingchallengeTopic\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"description\">Description:</label>\r\n");
      out.write("				                    <input id=\"description\" name=\"description\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			                <div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"CodingQuestion\">Question:</label>\r\n");
      out.write("				                    <input id=\"CodingQuestion\" name=\"CodingQuestion\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"function_desc\">Function Description:</label>\r\n");
      out.write("				                    <input id=\"function_desc\" name=\"function_desc\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			                <div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"input_format\">Input Format:</label>\r\n");
      out.write("				                    <input id=\"input_format\" name=\"input_format\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"input_format\">Output Format:</label>\r\n");
      out.write("				                    <input id=\"output_format\" name=\"output_format\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			                <div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"sample_input\">Sample Input:</label>\r\n");
      out.write("				                    <input id=\"sample_input\" name=\"sample_input\" required></input> \r\n");
      out.write("				                </div>\r\n");
      out.write("				                <div class=\"form-div\"> \r\n");
      out.write("				                    <label for=\"required_output\">Required Output:</label>\r\n");
      out.write("				                    <input id=\"required_output\" name=\"required_output\" required></input>\r\n");
      out.write("				                </div>\r\n");
      out.write("				            </div>\r\n");
      out.write("				                <div class=\"form-div\">\r\n");
      out.write("				                    <label for=\"explanation\">Explanation:</label>\r\n");
      out.write("				                    <input id=\"explanation\" name=\"explanation\" required style=\"width: 98%\"></input>\r\n");
      out.write("				                </div>  \r\n");
      out.write("			                <button type=\"submit\" value=\"Submit\" style=\"margin-left: 10px; margin-top: 20px; background-color: #ffa200; color: #002233;\">Add Challenge</button>\r\n");
      out.write("			            </form>\r\n");
      out.write("			    	");
 } else { 
      out.write("\r\n");
      out.write("			    		<form action=\"AddQuizQuestion\" method=\"post\" style=\"margin: 0px; padding: 0px;\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentTopic\" name=\"CodingAssessmentTopic\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentInstruction\" name=\"CodingAssessmentInstruction\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentDate\" name=\"CodingAssessmentDate\">\r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentLastDate\" name=\"CodingAssessmentLastDate\"> \r\n");
      out.write("			            	<input type=\"hidden\" id=\"CodingAssessmentDuration\" name=\"CodingAssessmentDuration\">\r\n");
      out.write("			            	\r\n");
      out.write("			            	 <div class=\"form-div\">\r\n");
      out.write("						        <label for=\"question\">Question:</label>\r\n");
      out.write("						        <input id=\"question\" name=\"question\" required style=\"width: 98%\"></input>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("							    <div class=\"form-div\">\r\n");
      out.write("							        <label for=\"option1\">Option 1:</label>\r\n");
      out.write("							        <input id=\"option1\" name=\"option1\" required oninput=\"updateCorrectOption(this.value, 'correctOption1')\">\r\n");
      out.write("							    </div>\r\n");
      out.write("							    <div class=\"form-div\">\r\n");
      out.write("							        <label for=\"option2\">Option 2:</label>\r\n");
      out.write("							        <input id=\"option2\" name=\"option2\" required oninput=\"updateCorrectOption(this.value, 'correctOption2')\">\r\n");
      out.write("							    </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div style=\"display: flex; gap: 20px;\">\r\n");
      out.write("							    <div class=\"form-div\">\r\n");
      out.write("							        <label for=\"option3\">Option 3:</label>\r\n");
      out.write("							        <input id=\"option3\" name=\"option3\" required oninput=\"updateCorrectOption(this.value, 'correctOption3')\">\r\n");
      out.write("							    </div>\r\n");
      out.write("							    <div class=\"form-div\">\r\n");
      out.write("							        <label for=\"option4\">Option 4:</label>\r\n");
      out.write("							        <input id=\"option4\" name=\"option4\" required oninput=\"updateCorrectOption(this.value, 'correctOption4')\">\r\n");
      out.write("							    </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-div\">\r\n");
      out.write("							    <label for=\"correctOption\">Correct Option:</label>\r\n");
      out.write("							    <select id=\"correctOption\" name=\"correctOption\" required style=\"width: 98%; padding: 10px; margin: 10px 0px; border: 2px solid #000; border-radius: 5px; font-weight: bold;\">\r\n");
      out.write("							        <option id=\"correctOption1\">Option 1</option>\r\n");
      out.write("							        <option id=\"correctOption2\">Option 2</option>\r\n");
      out.write("							        <option id=\"correctOption3\">Option 3</option>\r\n");
      out.write("							        <option id=\"correctOption4\">Option 4</option>\r\n");
      out.write("							    </select>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<script type=\"text/javascript\">\r\n");
      out.write("							    function updateCorrectOption(value, optionId) {\r\n");
      out.write("							        document.getElementById(optionId).innerText = value;\r\n");
      out.write("							    }\r\n");
      out.write("							</script>\r\n");
      out.write("						    \r\n");
      out.write("			                <button type=\"submit\" value=\"Submit\" style=\"margin-left: 10px; margin-top: 20px; background-color: #ffa200; color: #002233;\">Add Question</button>\r\n");
      out.write("			            </form>\r\n");
      out.write("			    	");
 } 
      out.write("\r\n");
      out.write("		        </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("         \r\n");
      out.write("        <div id=\"deleteAssessment\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal content -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"max-width: 300px; margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);\">\r\n");
      out.write("                <form id=\"delete-assessment\" action=\" \" method=\"post\">\r\n");
      out.write("                    <p style=\"color: black\">Do you want to delete Assessment ?</p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px; align-item: center\"> \r\n");
      out.write("                    	<input type=\"hidden\" name=\"module\" value=\"");
      out.print( module );
      out.write("\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #ffa200; border: none\" value=\"Yes\"\r\n");
      out.write("                            onclick=\"deleteAssessment()\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #d2d2e0; border: none\" value=\"No\"\r\n");
      out.write("                            onclick=\"closeModal('deleteAssessment')\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"logoutModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal content -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"max-width: 300px; margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);\">\r\n");
      out.write("                <form id=\"logoutForm\" action=\"TeacherLogout\">\r\n");
      out.write("                    <p style=\"color: black\">Are you sure, you want to Logout ?</p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px; align-item: center\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #ffa200; border: none\" value=\"Yes\"\r\n");
      out.write("                            onclick=\"logOut()\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #d2d2e0; border: none\" value=\"Cancel\"\r\n");
      out.write("                            onclick=\"closeModal('logoutModal')\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"changeLastDate\" class=\"modal-container\">\r\n");
      out.write("		    <!-- Modal Login -->\r\n");
      out.write("		    <div class=\"modal-content\" style=\"max-width: 550px; margin: auto; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); font-weight: bold;\">\r\n");
      out.write("		        <span style=\"color: black\" onclick=\"closeModal('changeLastDate')\" class=\"close\">&times;</span>\r\n");
      out.write("		        <h2 style=\"text-align: center; color: black\">Update Submission Date :</h2>\r\n");
      out.write("		        <div class=\"add-challenge\">\r\n");
      out.write("		            <form action=\" \" method=\"post\" style=\"margin: 0px; padding: 0px;\">\r\n");
      out.write("		            	 <div class=\"form-div\" style=\"display: flex; align-items: center; justify-content: center;\"> \r\n");
      out.write("							<div style=\"margin-left: 10px;\">\r\n");
      out.write("								<input type=\"hidden\" name=\"module\" value=\"");
      out.print( module );
      out.write("\">\r\n");
      out.write("								<label for=\"newLastdate\">Last Date :</label>\r\n");
      out.write("								<input type=\"date\" id=\"newLastdate\" name=\"newLastdate\" required style=\"width: 200px\"></input> \r\n");
      out.write("							</div>\r\n");
      out.write("							<button type=\"submit\" value=\"Submit\" style=\"margin-left: 20px; background-color: #ffa200; color: #002233;\">Update</button>\r\n");
      out.write("						</div>  \r\n");
      out.write("		                \r\n");
      out.write("		            </form>\r\n");
      out.write("		        </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function openModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	        }\r\n");
      out.write("	\r\n");
      out.write("	        function closeModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'none';\r\n");
      out.write("	        }  \r\n");
      out.write("	        \r\n");
      out.write("	        function logOut() {\r\n");
      out.write("                document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("            }\r\n");
      out.write("	        \r\n");
      out.write("	        function deleteAssessment() {\r\n");
      out.write("	        	document.getElementById(\"delete-assessment\").submit();\r\n");
      out.write("	        }\r\n");
      out.write("	        \r\n");
      out.write("	        function openCodingModal() {\r\n");
      out.write("	             \r\n");
      out.write("	            var topicInput = document.getElementById(\"topic\");\r\n");
      out.write("	            var instructionInput = document.getElementById(\"Instruction\");\r\n");
      out.write("	            var assignedDateInput = document.getElementById(\"assignedDate\");\r\n");
      out.write("	            var lastDateInput = document.getElementById(\"lastDate\");\r\n");
      out.write("	            var durationInput = document.getElementById(\"duration\");\r\n");
      out.write("\r\n");
      out.write("	            var topic = topicInput.value.trim();\r\n");
      out.write("	            var instruction = instructionInput.value.trim();\r\n");
      out.write("	            var assignedDate = assignedDateInput.value.trim();\r\n");
      out.write("	            var lastDate = lastDateInput.value.trim();\r\n");
      out.write("	            var duration = durationInput.value.trim();\r\n");
      out.write("\r\n");
      out.write("	            if (topic === '') {\r\n");
      out.write("	                topicInput.style.borderColor = 'red';\r\n");
      out.write("	                return;\r\n");
      out.write("	            } else {\r\n");
      out.write("	                topicInput.style.borderColor = '';\r\n");
      out.write("	            }\r\n");
      out.write("\r\n");
      out.write("	            if (instruction === '') {\r\n");
      out.write("	                instructionInput.style.borderColor = 'red';\r\n");
      out.write("	                return;\r\n");
      out.write("	            } else {\r\n");
      out.write("	                instructionInput.style.borderColor = '';\r\n");
      out.write("	            }\r\n");
      out.write("\r\n");
      out.write("	            if (assignedDate === '') {\r\n");
      out.write("	                assignedDateInput.style.borderColor = 'red';\r\n");
      out.write("	                return;\r\n");
      out.write("	            } else {\r\n");
      out.write("	                assignedDateInput.style.borderColor = '';\r\n");
      out.write("	            }\r\n");
      out.write("\r\n");
      out.write("	            if (lastDate === '') {\r\n");
      out.write("	                lastDateInput.style.borderColor = 'red';\r\n");
      out.write("	                return;\r\n");
      out.write("	            } else {\r\n");
      out.write("	                lastDateInput.style.borderColor = '';\r\n");
      out.write("	            }\r\n");
      out.write("\r\n");
      out.write("	            if (duration === '') {\r\n");
      out.write("	                durationInput.style.borderColor = 'red';\r\n");
      out.write("	                return;\r\n");
      out.write("	            } else {\r\n");
      out.write("	                durationInput.style.borderColor = '';\r\n");
      out.write("	            }\r\n");
      out.write("	            \r\n");
      out.write("	            var CodingAssessmentTopic = document.getElementById(\"CodingAssessmentTopic\");\r\n");
      out.write("	            var CodingAssessmentInstruction = document.getElementById(\"CodingAssessmentInstruction\");\r\n");
      out.write("	            var CodingAssessmentDate = document.getElementById(\"CodingAssessmentDate\");\r\n");
      out.write("	            var CodingAssessmentLastDate = document.getElementById(\"CodingAssessmentLastDate\");\r\n");
      out.write("	            var CodingAssessmentDuration = document.getElementById(\"CodingAssessmentDuration\");\r\n");
      out.write("				\r\n");
      out.write("	            console.log(\"CodingAssessmentTopic\"+topic);\r\n");
      out.write("	            console.log(\"CodingAssessmentDate\"+assignedDate);\r\n");
      out.write("	            \r\n");
      out.write("	            CodingAssessmentTopic.value = topic;\r\n");
      out.write("	            CodingAssessmentInstruction.value = instruction;\r\n");
      out.write("	            CodingAssessmentDate.value = assignedDate;\r\n");
      out.write("	            CodingAssessmentLastDate.value = lastDate;\r\n");
      out.write("	            CodingAssessmentDuration.value = duration;\r\n");
      out.write("	            \r\n");
      out.write("	            var modal = document.getElementById(\"addChallenge\");\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	            \r\n");
      out.write("	        }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        	function changeLastDate() {\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <footer style=\"background-color: #002233; display: flex; justify-content: space-between; margin: 0px 50px; color: #ffa200;\">\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>About Us</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<p>Technolearn Trainings is one of the best training institutes in Sinhagad Road/Anand Nagar, Pune. We provide professional courses for students, working professionals, job seekers and corporate employees with placement assurance.</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Features</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<a href=\"teacherHome.jsp\">Technology Roadmaps</a><p></p>\r\n");
      out.write("	                <a href=\"videoLecture.jsp\">Video Lectures</a><p></p>\r\n");
      out.write("	                <a href=\"codingEnhancement.jsp\">Coding Enhancement</a><p></p>\r\n");
      out.write("	                <a href=\"technicalQuiz.jsp\">Technical Quiz</a><p></p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Contact </h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<div style=\"margin-top: 20px;\">\r\n");
      out.write("                    <img src=\"./media/pin.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("                    <span id=\"tick-text\">Technolearn Trainings 133, Peshwa, 2nd Floor, Office No. 09, Near Chaitanya Hospital, Next to Parvati Bridge, Sinhgad Road, Parvati, Pune - 411030.</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/phone.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">91 88570 96492</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/email (1).png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">Info.technolearn@gmail.com</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Follow Us</h4>\r\n");
      out.write("        		<div class=\"footer-social-media\">\r\n");
      out.write("        			<a href=\"#\"><img src=\"./media/twitter.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/facebook.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/linkedin.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/instagram.png\"></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
