/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-18 15:45:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import techcraft.model.CodingProgress;
import techcraft.dao.CodingDao;
import techcraft.model.Coding;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import techcraft.model.Coding;
import java.util.List;

public final class codingQuestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("techcraft.dao.CodingDao");
    _jspx_imports_classes.add("techcraft.model.Coding");
    _jspx_imports_classes.add("techcraft.model.CodingProgress");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("org.hibernate.cfg.Configuration");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        <script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    	.dashboard-heading {\r\n");
      out.write("			margin: 10px 20px;\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.dashboard-heading span { \r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.about {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			flex-direction: column;\r\n");
      out.write("			flex: 1;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.progress b {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			font-size: 13px; \r\n");
      out.write("		}\r\n");
      out.write("	    .progress-container { \r\n");
      out.write("	        width: 300px;\r\n");
      out.write("	        height: 10px;\r\n");
      out.write("	        background-color: #002233;\r\n");
      out.write("	        border-radius: 5px; \r\n");
      out.write("	        margin: 10px; \r\n");
      out.write("	    }\r\n");
      out.write("	    .progress-barr {\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        height: 100%;\r\n");
      out.write("	        background-color: #0bbfff;\r\n");
      out.write("	        border-radius: 5px;\r\n");
      out.write("	        transition: width 1s ease;\r\n");
      out.write("	    }\r\n");
      out.write("	    .progress-text {  \r\n");
      out.write("	        color: #000;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	        font-size: 30px;\r\n");
      out.write("	        margin: 10px;\r\n");
      out.write("	        margin-bottom: 0px;\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main {\r\n");
      out.write("			width: auto;\r\n");
      out.write("		    height: auto;\r\n");
      out.write("		    background-size: cover; \r\n");
      out.write("		    border: 3px solid #000;\r\n");
      out.write("		    border-radius: 20px; \r\n");
      out.write("		    background-image: url(\"./media/techback.jpg\");\r\n");
      out.write("		    margin: 0px 20px;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.roadmap-main fieldset {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			margin: 30px;\r\n");
      out.write("			background-color: #002233; \r\n");
      out.write("			border: solid 4px #000;\r\n");
      out.write("			border-radius: 20px;\r\n");
      out.write("			height: auto;\r\n");
      out.write("			margin-top: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.challenge {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			border: solid 2px #000;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			border-radius: 20px;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			margin: 20px;\r\n");
      out.write("			padding: 20px 40px;\r\n");
      out.write("			font-size: 13px;\r\n");
      out.write("			color: black;\r\n");
      out.write("			transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.challenge:hover {\r\n");
      out.write("			transform: scale(1.01);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.challenge span {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.challenge button {\r\n");
      out.write("			color: #fff;\r\n");
      out.write("	        cursor: pointer;\r\n");
      out.write("	        font-weight: bold; \r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("	        background-color: #ffa200;\r\n");
      out.write("	        letter-spacing: 1px; \r\n");
      out.write("	        padding: 15px 40px;\r\n");
      out.write("	        margin: 10px; \r\n");
      out.write("	        font-size: 15px;\r\n");
      out.write("	        border: none;\r\n");
      out.write("	        transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.challenge button:hover {\r\n");
      out.write("			color: #fff;\r\n");
      out.write("			transform: scale(1.1);   \r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("     \r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    	");

	        String name = (String) session.getAttribute("name");
	        if (name == null) {
	            response.sendRedirect("index.jsp");
	        } else {
	    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"studentHome.jsp\" style=\"margin-top: 10px; color: #fff\">Technology Roadmaps</a>\r\n");
      out.write("                <a href=\"videoLecture.jsp\" style=\"margin-top: 10px; color: #fff\">Video Lectures</a>\r\n");
      out.write("                <a href=\"codingInhancement.jsp\" style=\"border-bottom: 2px solid #ffa200; margin-top: 10px; padding-bottom: 10px;\">Coding Enhancement</a>\r\n");
      out.write("                <a href=\"technicalQuiz.jsp\" style=\"margin-top: 10px; color: #fff\">Technical Quiz</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1; margin-right: 0px;\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 15px\">\r\n");
      out.write("        	<div class=\"popup\">\r\n");
      out.write("			  <label for=\"user\" class=\"userName\">");
      out.print( name );
      out.write("<img class=\"dropdown-icon\" alt=\"\" src=\"./media/play.png\"></label>    \r\n");
      out.write("			  <div class=\"popup-content\">\r\n");
      out.write("			    <a href=\"studentProfile.jsp\">Profile</a>\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"assessment.jsp\">Assessment</a> \r\n");
      out.write("			    <!-- <p></p>\r\n");
      out.write("			    <a href=\"Placement.jsp\">Placement</a>-->\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"Feedback.jsp\">Feedback</a>\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"#\" onclick=\"openModal('logoutModal')\">Logout</a>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("        	\r\n");
      out.write("        </header>\r\n");
      out.write("        <div style=\"width: 100%; height: 100px;\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard-heading\">\r\n");
      out.write("        	<span style=\"font-size: 15px; color: #888888\">Dashboard:</span>\r\n");
      out.write("        	<span style=\"color: white\"> Coding Enhancement</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"roadmap-main\">\r\n");
      out.write("        	<div class=\"roadmap-heading\">\r\n");
      out.write("        		<p>At TechCraft Learning Hub, we believe in empowering learners to enhance their coding skills through structured programs that guide them on their coding journey.</p> \r\n");
      out.write("        		<div style=\"display: flex; margin: 0px 50px; margin-top: 20px;\">\r\n");
      out.write("	        		<div class=\"dashboard-heading\" style=\"margin: 10px 10px;\"> \r\n");
      out.write("	        			");
 String buttonValue = request.getParameter("submitButton"); 
      out.write("\r\n");
      out.write("			        	<span style=\"font-size: 15px; color: #888888\">prepare:</span>\r\n");
      out.write("			        	<span style=\"color: black; font-size: 25px;\">");
      out.print( buttonValue );
      out.write("</span>\r\n");
      out.write("			        </div> \r\n");
      out.write("			        <span style=\"flex: 1\"></span>\r\n");
      out.write("			        <div style=\"display: flex;\">\r\n");
      out.write("						<div class=\"progress\">\r\n");
      out.write("							<b id=\"completed\">Complete all to get your Certificate !</b>\r\n");
      out.write("							<a id=\"get-certificate\" href=\"studentProfile.jsp\" style=\"display: none; color: #0bbfff; text-decoration: none;\"><b>Certificate !</b></a>\r\n");
      out.write("							<div class=\"progress-container\">\r\n");
      out.write("							    <div class=\"progress-barr\" id=\"progressBar\"></div>\r\n");
      out.write("							</div> \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"progress-text\" id=\"progressText\"></div> \r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("        		<fieldset>\r\n");
      out.write("					");
  
						SessionFactory factory = new Configuration().configure().buildSessionFactory();
						Session studentSession = factory.openSession();
						Transaction transaction = null;
						            
						try {
							transaction = studentSession.beginTransaction();
						                
						    Query<Coding> query = studentSession.createQuery("FROM Coding where technology = :technology", Coding.class);
						    query.setParameter("technology", buttonValue);
						    List<Coding> challenges = query.getResultList();
						
						    for (int i = 0; i < challenges.size(); i++) {
						    	Coding coding = challenges.get(i);
					
      out.write("\r\n");
      out.write("					            <div class=\"challenge\">\r\n");
      out.write("					            	<div style=\"max-width: 900px;\">\r\n");
      out.write("					            		<p>Challenge ");
      out.print( i + 1 );
      out.write("</p>\r\n");
      out.write("					            		<span>");
      out.print( coding.getTopic() );
      out.write("</span>\r\n");
      out.write("					            		<p>");
      out.print( coding.getDescription() );
      out.write("</p>\r\n");
      out.write("					            	</div>\r\n");
      out.write("					            	<span style=\"flex: 1;\"></span>\r\n");
      out.write("					            	\r\n");
      out.write("					            	");
 
									    try { 
									        SessionFactory factory1 = new Configuration().configure().buildSessionFactory();
									        Session studentSession1 = factory.openSession();
									        
									        Query<CodingProgress> query1 = studentSession.createQuery("FROM CodingProgress WHERE studentName = :studentName AND technology = :technology AND topic = :topic", CodingProgress.class);
									        query1.setParameter("studentName", name);
									        query1.setParameter("technology", buttonValue);
									        query1.setParameter("topic", coding.getTopic());
									        CodingProgress existingProgress = query1.uniqueResult();
									
									        if (existingProgress == null) {
									
      out.write("\r\n");
      out.write("									            <form action=\"codeCompiler.jsp\"> \r\n");
      out.write("									                <input type=\"hidden\" name=\"technology\" value=\"");
      out.print( buttonValue );
      out.write("\">\r\n");
      out.write("									                <button type=\"submit\" name=\"challenge\" value=\"");
      out.print( coding.getTopic() );
      out.write("\">Solve Challenge</button>\r\n");
      out.write("									            </form>\r\n");
      out.write("									");
   
									        } else {
									
      out.write("\r\n");
      out.write("									            <form action=\"codeCompiler.jsp\"> \r\n");
      out.write("									                <input type=\"hidden\" name=\"technology\" value=\"");
      out.print( buttonValue );
      out.write("\">\r\n");
      out.write("									                <button type=\"submit\" name=\"challenge\" value=\"");
      out.print( coding.getTopic() );
      out.write("\" style=\"background-color: #0bbfff; color: white;\">Challenge Solved !</button>\r\n");
      out.write("									            </form>\r\n");
      out.write("									");
 
									        } 
									        studentSession1.close();
									        factory1.close();
									    } 
					            	catch (Exception e) {
									        e.printStackTrace(); 
									    }
									
      out.write(" \r\n");
      out.write("					            </div>\r\n");
      out.write("		            ");
 
						        }
						        transaction.commit();
						   } 
						   catch (Exception e) { 
						        if (transaction != null) {
						            transaction.rollback();
						        }
						        e.printStackTrace();
						   } 
						   finally {
						        studentSession.close();
						        factory.close();
						   }
					
      out.write("\r\n");
      out.write("		        </fieldset>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div id=\"logoutModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal content -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"max-width: 300px;\">\r\n");
      out.write("                <form id=\"logoutForm\" action=\"StudentLogout\">\r\n");
      out.write("                    <p style=\"color: black\">Are you sure, you want to Logout ?</p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px; align-item: center\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #ffa200; border: none\" value=\"Yes\"\r\n");
      out.write("                            onclick=\"logOut()\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #d2d2e0; border: none\" value=\"Cancel\"\r\n");
      out.write("                            onclick=\"closeModal('logoutModal')\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <form id=\"generate-certificate\" action=\"GenerateCertificate\" method=\"post\">\r\n");
      out.write("        	<input type=\"hidden\" name=\"name\" value=\"");
      out.print( name );
      out.write("\">\r\n");
      out.write("        	<input type=\"hidden\" name=\"type\" value=\"Coding\">\r\n");
      out.write("        	<input type=\"hidden\" name=\"technology\" value=\"");
      out.print( buttonValue );
      out.write("\"> \r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function openModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	        }\r\n");
      out.write("	\r\n");
      out.write("	        function closeModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'none';\r\n");
      out.write("	        }  \r\n");
      out.write("	        \r\n");
      out.write("	        function logOut() {\r\n");
      out.write("                document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        ");

        	int totalChallenges = CodingDao.totalChallenges(buttonValue);
        	int totalSubmitedChllenges = CodingDao.totalSubmittedChallenges(buttonValue, name);
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("		    if (");
      out.print( totalSubmitedChllenges );
      out.write(" === ");
      out.print( totalChallenges );
      out.write("  && ");
      out.print( totalSubmitedChllenges );
      out.write(" != 0 && ");
      out.print( totalChallenges );
      out.write(" != 0) {\r\n");
      out.write("		        Swal.fire({\r\n");
      out.write("		            title: \"Congrats!\",\r\n");
      out.write("		            text: \"Progress Completed, Collect your Certificate!\",\r\n");
      out.write("		            icon: \"success\",\r\n");
      out.write("		            showConfirmButton: false,\r\n");
      out.write("		            timer: 2500\r\n");
      out.write("		        });\r\n");
      out.write("		        console.log(\"certificate adding\");\r\n");
      out.write("		        const name = \"");
      out.print( name );
      out.write("\";\r\n");
      out.write("		        const type = \"Coding\";\r\n");
      out.write("		        const technology = \"");
      out.print( buttonValue );
      out.write("\";\r\n");
      out.write(" \r\n");
      out.write("		        const uniqueKey = name+type+technology;\r\n");
      out.write("\r\n");
      out.write("		        //localStorage.removeItem(uniqueKey);\r\n");
      out.write("		        if (!localStorage.getItem(uniqueKey)) { \r\n");
      out.write("		            localStorage.setItem(uniqueKey, 'true'); \r\n");
      out.write("		            document.getElementById('generate-certificate').submit();\r\n");
      out.write("		            console.log(\"certificate added\");\r\n");
      out.write("		        }\r\n");
      out.write("		    }\r\n");
      out.write("		    else if (");
      out.print( totalChallenges );
      out.write(" == 0) {\r\n");
      out.write("		    	Swal.fire({\r\n");
      out.write("		            title: \"Oops Sorry!\",\r\n");
      out.write("		            text: \"There is nothing right Now!\",\r\n");
      out.write("		            icon: \"info\",\r\n");
      out.write("		            showConfirmButton: false,\r\n");
      out.write("		            timer: 2500\r\n");
      out.write("		        });\r\n");
      out.write("		    }\r\n");
      out.write("		</script>\r\n");
      out.write("         \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("		    const progressBar = document.getElementById('progressBar');\r\n");
      out.write("		    const progressText = document.getElementById('progressText');\r\n");
      out.write("		     \r\n");
      out.write("		    let width = 0;\r\n");
      out.write("		    const interval = setInterval(() => {\r\n");
      out.write("		        if (width == 100) {\r\n");
      out.write("		        	const completed = document.getElementById('completed');\r\n");
      out.write("		        	const getcertificate = document.getElementById('get-certificate');\r\n");
      out.write("		        	\r\n");
      out.write("		        	completed.innerText = \"Completed, collect your \";\r\n");
      out.write("		        	getcertificate.style.display = 'inline-block';\r\n");
      out.write("		        	clearInterval(interval); \r\n");
      out.write("		        } \r\n");
      out.write("		        else {\r\n");
      out.write("		        	if(");
      out.print(totalSubmitedChllenges );
      out.write(" == 0 && ");
      out.print(totalChallenges );
      out.write(" == 0) {\r\n");
      out.write("		        		progressBar.style.width = 0 + '%'; \r\n");
      out.write("			            progressText.innerText = 0 + '%';\r\n");
      out.write("		        	}\r\n");
      out.write("		        	else {\r\n");
      out.write("		        		 width = (");
      out.print(totalSubmitedChllenges );
      out.write('/');
      out.print(totalChallenges );
      out.write(") * 100;\r\n");
      out.write("				         progressBar.style.width = width + '%'; \r\n");
      out.write("				         progressText.innerText = width.toFixed(0) + '%';\r\n");
      out.write("		        	} \r\n");
      out.write("		        }\r\n");
      out.write("		    }, 50);\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("        <footer style=\"background-color: #002233; display: flex; justify-content: space-between; margin: 0px 50px; color: #ffa200;\">\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>About Us</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<p>Technolearn Trainings is one of the best training institutes in Sinhagad Road/Anand Nagar, Pune. We provide professional courses for students, working professionals, job seekers and corporate employees with placement assurance.</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Features</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<a href=\"studentHome.jsp\">Technology Roadmaps</a><p></p>\r\n");
      out.write("	                <a href=\"videoLecture.jsp\">Video Lectures</a><p></p>\r\n");
      out.write("	                <a href=\"codingInhancement.jsp\">Coding Enhancement</a><p></p>\r\n");
      out.write("	                <a href=\"technicalQuiz.jsp\">Technical Quiz</a><p></p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Contact </h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<div style=\"margin-top: 20px;\">\r\n");
      out.write("                    <img src=\"./media/pin.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("                    <span id=\"tick-text\">Technolearn Trainings 133, Peshwa, 2nd Floor, Office No. 09, Near Chaitanya Hospital, Next to Parvati Bridge, Sinhgad Road, Parvati, Pune - 411030.</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/phone.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">91 88570 96492</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/email (1).png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">Info.technolearn@gmail.com</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Follow Us</h4>\r\n");
      out.write("        		<div class=\"footer-social-media\">\r\n");
      out.write("        			<a href=\"#\"><img src=\"./media/twitter.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/facebook.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/linkedin.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/instagram.png\"></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        <button onclick=\"scrollToTop()\" id=\"scrollBtn\" title=\"Go to top\"><img class=\"go-top\" alt=\"\" src=\"./media/play.png\"></button>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\"> \r\n");
      out.write("		var mybutton = document.getElementById(\"scrollBtn\"); \r\n");
      out.write("		window.onscroll = function() {scrollFunction()};\r\n");
      out.write("\r\n");
      out.write("		function scrollFunction() {\r\n");
      out.write("		  if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {\r\n");
      out.write("		    mybutton.style.display = \"block\";\r\n");
      out.write("		  } else {\r\n");
      out.write("		    mybutton.style.display = \"none\";\r\n");
      out.write("		  }\r\n");
      out.write("		} \r\n");
      out.write("		function scrollToTop() { \r\n");
      out.write("		  document.documentElement.scrollTop = 0; \r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
