/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-22 09:29:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import techcraft.model.Feedback;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("techcraft.model.Feedback");
    _jspx_imports_classes.add("org.hibernate.cfg.Configuration");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        <script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("     \r\n");
      out.write("    	.progress-bar {\r\n");
      out.write("		    width: 20px;\r\n");
      out.write("		    height: 20px;\r\n");
      out.write("		    margin-right: 20px; \r\n");
      out.write("		    margin-left: 20px;\r\n");
      out.write("		    border-radius: 50%;\r\n");
      out.write("		    border: 4px solid black;\r\n");
      out.write("		    border-top-color: #ffa200;\r\n");
      out.write("		    animation: spin 1s linear infinite;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.hidden {\r\n");
      out.write("		    display: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes spin {\r\n");
      out.write("		    0% { transform: rotate(0deg); }\r\n");
      out.write("		    100% { transform: rotate(360deg); }\r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("    	.student-details { \r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 12px;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			height: 500px;\r\n");
      out.write("			overflow-y: auto; \r\n");
      out.write("			padding-right: 50px;  \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.student-details img {\r\n");
      out.write("			width: 550px;\r\n");
      out.write("			height: 550px;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("        table {\r\n");
      out.write("		    width: 100%;\r\n");
      out.write("		    border-collapse: collapse;\r\n");
      out.write("		    font-size: 13px;\r\n");
      out.write("		    background-color: #002233;\r\n");
      out.write("		    color: white;  \r\n");
      out.write("		    border-radius: 20px;\r\n");
      out.write("		    margin: 20px; \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		tr {\r\n");
      out.write("		    background-color: #fff;\r\n");
      out.write("		    color: black;  \r\n");
      out.write("		    margin: 10px; \r\n");
      out.write("		    text-align: center; \r\n");
      out.write("		    transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		tr:hover {\r\n");
      out.write("			transform: scale(1.01);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		td {  \r\n");
      out.write("		    border: none;\r\n");
      out.write("		    padding: 40px;  \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		th {\r\n");
      out.write("			background-color: #002233;\r\n");
      out.write("			color: #fff;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			padding: 10px; \r\n");
      out.write("			border: none; \r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("		\r\n");
      out.write("    <body>\r\n");
      out.write("    	\r\n");
      out.write("    	");
 
	        String status = (String)request.getAttribute("status");
	        if (status != null && status.equals("Success")) {
	    
      out.write("\r\n");
      out.write("	            <script type=\"text/javascript\">\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		            	title: \"Congrates !\",\r\n");
      out.write("		            	text: \"Acount Created Successfully !\",\r\n");
      out.write("		            	icon: \"success\",\r\n");
      out.write("		            	showConfirmButton: false,\r\n");
      out.write("		            	timer: 2500,\r\n");
      out.write("	            	});\r\n");
      out.write("	            </script>\r\n");
      out.write("	    ");

	        }
	        if (status != null && status.equals("failed")) {
	    
      out.write("\r\n");
      out.write("	    	            <script type=\"text/javascript\">\r\n");
      out.write("	    		            Swal.fire({\r\n");
      out.write("	    		            	title: \"Email already Exist !\",\r\n");
      out.write("	    		            	text: \"Please select different email !\",\r\n");
      out.write("	    		            	icon: \"error\",\r\n");
      out.write("	    		            	showConfirmButton: false,\r\n");
      out.write("	    		            	timer: 3000,\r\n");
      out.write("	    	            	});\r\n");
      out.write("	    	            </script>\r\n");
      out.write("	    ");

	        }
	        if (status != null && status.equals("error")) {
	    
      out.write("\r\n");
      out.write("	    		<script type=\"text/javascript\">\r\n");
      out.write("	    		            Swal.fire({\r\n");
      out.write("	    		            	title: \"Sign In Failed !\",\r\n");
      out.write("	    		            	text: \"Wrong Email or Password !\",\r\n");
      out.write("	    		            	icon: \"error\",\r\n");
      out.write("	    		            	showConfirmButton: false,\r\n");
      out.write("	    		            	timer: 2500,\r\n");
      out.write("	    	            	});\r\n");
      out.write("	    	    </script>\r\n");
      out.write("	     ");

	    	}
	        if (status != null && status.equals("found")) {
	   	 
      out.write("\r\n");
      out.write("	    	    		<script type=\"text/javascript\">\r\n");
      out.write("	    	    		            Swal.fire({\r\n");
      out.write("	    	    		            	title: \"Check Email !\",\r\n");
      out.write("	    	    		            	text: \"Your credentials have been sent to the registered email address!\",\r\n");
      out.write("	    	    		            	icon: \"success\",\r\n");
      out.write("	    	    		            	showConfirmButton: false,\r\n");
      out.write("	    	    		            	timer: 3000,\r\n");
      out.write("	    	    	            	});\r\n");
      out.write("	    	    	    </script>\r\n");
      out.write("	    ");

	    	}
	        if (status != null && status.equals("notFound")) {
	    	    
      out.write("\r\n");
      out.write("	    	    		<script type=\"text/javascript\">\r\n");
      out.write("	    	    		            Swal.fire({\r\n");
      out.write("	    	    		            	title: \"Email not registed !\",\r\n");
      out.write("	    	    		            	text: \"Please Register to TechCraft !\",\r\n");
      out.write("	    	    		            	icon: \"error\",\r\n");
      out.write("	    	    		            	showConfirmButton: false,\r\n");
      out.write("	    	    		            	timer: 2500,\r\n");
      out.write("	    	    	            	});\r\n");
      out.write("	    	    	    </script>\r\n");
      out.write("	    ");

	   		}
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"index.jsp\">Home</a>\r\n");
      out.write("                <a onclick=\"openModal('AboutModel')\">About</a>\r\n");
      out.write("                <a href=\"#\">Contact</a>\r\n");
      out.write("                <a onclick=\"openModal('feedbackModel')\">Feedback</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 20px\">\r\n");
      out.write("            <span onclick=\"openModal('loginModal')\">Sign In</span>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"width: 100%; height: 100px;\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"about\">\r\n");
      out.write("                <h1>Welcome to TechCraft</h1>\r\n");
      out.write("                <p style=\"font-weight: bold;\">TechCraft Learning Hub is an online learning platform that helps you to\r\n");
      out.write("                    learn and develop your skills.</p> <!-- Corrected typo -->\r\n");
      out.write("                <p class=\"moto\" >An innovative online learning hub designed to empower individuals with the skills and\r\n");
      out.write("                    knowledge needed to excel in the rapidly evolving world of technology. Our platform offers a\r\n");
      out.write("                    comprehensive range of resources, including technology roadmaps, video lectures, coding enhancement\r\n");
      out.write("                    tools, and technical quizzes, aimed at catering to learners of all levels, from beginners to\r\n");
      out.write("                    advanced professionals !</p>\r\n");
      out.write("                <button onClick=\"openModal('registrationModal')\">Get Started<img src=\"./media/play.png\"\r\n");
      out.write("                        style=\"margin-left: 10px; margin-top: 5px; width: 15px; height: 15px\"></button>\r\n");
      out.write("                <p style=\"color: #002133; font-size: 15px\">Join our community today and start your journey towards\r\n");
      out.write("                    mastering the latest technologies !</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img src=\"./media/freelancer.svg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button onclick=\"scrollToTop()\" id=\"scrollBtn\" title=\"Go to top\"><img class=\"go-top\" alt=\"\" src=\"./media/play.png\"></button>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"features\">\r\n");
      out.write("        	<img alt=\"\" src=\"./media/organizational-agility.svg\">\r\n");
      out.write("        	<div>\r\n");
      out.write("        		<h1>Technology Roadmaps</h1>\r\n");
      out.write("        		<div class=\"feature\" style=\"background-color:#ff9900;\">\r\n");
      out.write("	        		<h4>Technology Roadmaps</h4>\r\n");
      out.write("	                <p>Our platform's technology roadmaps are meticulously crafted to guide learners through the intricacies of various technologies. Whether you're a novice or an experienced professional, our roadmaps provide clear pathways for skill acquisition and career progression. With curated resources and expert advice, you can navigate the ever-evolving landscape of technology with confidence. </p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"features\">\r\n");
      out.write("	        <div>\r\n");
      out.write("	        	<h1>Video Lectures</h1>\r\n");
      out.write("	        	<div class=\"feature\">\r\n");
      out.write("	        		<h4>Video Lectures</h4>\r\n");
      out.write("	                <p>Dive deep into the world of technology with our extensive library of video lectures. Delivered by industry experts, these lectures cover a diverse array of topics, ensuring that learners receive a comprehensive education. From foundational principles to cutting-edge advancements, our videos cater to individuals at every stage of their learning journey.</p>\r\n");
      out.write("	        	</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("        	<img alt=\"\" src=\"./media/website.svg\">\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"features\">\r\n");
      out.write("        	<img alt=\"\" src=\"./media/easter-egg-hunt.svg\">\r\n");
      out.write("        	<div>\r\n");
      out.write("        		<h1>Coding Enhancement</h1>\r\n");
      out.write("	        	<div class=\"feature\" style=\"background-color:#ff9900;\">\r\n");
      out.write("	        		<h4>Coding Enhancement</h4>\r\n");
      out.write("	                <p>Elevate your coding prowess with our suite of interactive tools designed to hone your skills. Whether you're brushing up on the basics or tackling advanced concepts, our platform provides the resources you need to excel. With real-time feedback and personalized recommendations, you can sharpen your coding abilities and unlock new opportunities in the digital realm.</p>\r\n");
      out.write("	        	</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"features\"> \r\n");
      out.write("        	<div>\r\n");
      out.write("        		<h1>Technical Quiz</h1>\r\n");
      out.write("	        	<div class=\"feature\">\r\n");
      out.write("	        		<h4>Technical Quiz</h4>\r\n");
      out.write("	                <p> Put your technical knowledge to the test with our engaging quizzes designed to challenge and educate. Covering a wide range of subjects, our quizzes offer insight into your strengths and areas for improvement. Whether you're preparing for exams or simply seeking to expand your understanding, our interactive quizzes are an invaluable tool for growth and learning.</p>\r\n");
      out.write("	        	</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<img alt=\"\" src=\"./media/task.svg\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"registrationModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal Registration -->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <span style=\"color: black\" onclick=\"closeModal('registrationModal')\" class=\"close\">&times;</span>\r\n");
      out.write("                <h2 style=\"text-align: center; color: black\">Sign Up</h2>\r\n");
      out.write("                <form id=\"register-user\" action=\"StudentRegistration\" method=\"post\">\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/black-user.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"text\" id=\"firstName\" name=\"firstName\" placeholder=\"First Name\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/black-user.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"text\" id=\"lastName\" name=\"lastName\" placeholder=\"Last Name\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/mobile.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"text\" id=\"number\" name=\"number\" placeholder=\"Mobile No\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/lock.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/confirm.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm Password\" required><br>\r\n");
      out.write("                	</div> \r\n");
      out.write("				    <div style=\"display: flex; align-items: center; text-align: center; margin-left: 35px\">\r\n");
      out.write("				    	<div class=\"register-container\">\r\n");
      out.write("				    		<input type=\"button\" class=\"register\" value=\"Sign Up\" id=\"signUpButton\" onclick=\"registerClicked('registrationModal')\" style=\"background-color: #ffa200\">\r\n");
      out.write("				    		<div class=\"progress-bar hidden\" id=\"proBar\"></div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("				        <p id=\"error\" style=\"font-size: 10px; color: red; margin-left: 20px;\"></p>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <hr>\r\n");
      out.write("				    <p style=\"text-align: center; color: black\">If already registered | <a onclick=\"openAndClose()\"\r\n");
      out.write("				            class=\"clickLogin\">Sign In</a> </p>\r\n");
      out.write("				    <div class=\"socialMedia\" style=\"display: flex\">\r\n");
      out.write("				        <img src=\"./media/Google.gif\" style=\"margin-left: 95px\">\r\n");
      out.write("				        <img src=\"./media/Facebook.gif\">\r\n");
      out.write("				        <img src=\"./media/Linkedin.gif\" onclick=\"toSocialAccount()\">\r\n");
      out.write("				        <img src=\"./media/Instagram.gif\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				</form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        	function toSocialAccount() {\r\n");
      out.write("        		window.location.href = \"https://www.linkedin.com/company/technolearn-trainings-institute/about/\";\r\n");
      out.write("        	}\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"AboutModel\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal about -->\r\n");
      out.write("            <div class=\"site-content\">\r\n");
      out.write("                <div style=\"padding: 20px; display: flex; border-radius: 10px\">\r\n");
      out.write("                    <img src=\"./media/success.svg\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span style=\"color: black\" onclick=\"closeModal('AboutModel')\" class=\"close\">&times;</span>\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #ffa200; animation: zoomInOut 0.5s infinite alternate;\">\r\n");
      out.write("                            About TechCraft</h2>\r\n");
      out.write("                        <p>TechCraft Learning Hub is an online learning platform that helps you to\r\n");
      out.write("                            learn and develop your skills.</p>\r\n");
      out.write("                        <p>Mission Statement:</p>\r\n");
      out.write("                        <div class=\"sub-about\">At TechCraft Learning Platform, our mission is to democratize access to\r\n");
      out.write("                            quality tech education and empower learners worldwide to achieve their professional goals.\r\n");
      out.write("                            We believe that by providing comprehensive learning resources and fostering a supportive\r\n");
      out.write("                            learning community, we can inspire individuals to pursue their passion for technology and\r\n");
      out.write("                            thrive in today's digital landscape.</div>\r\n");
      out.write("                        <p>Join Us Today:</p>\r\n");
      out.write("                        <div class=\"sub-about\">Embark on your learning journey with TechCraft Learning Platform and\r\n");
      out.write("                            unlock your full potential in the world of technology. Whether you're a student, a working\r\n");
      out.write("                            professional, or a tech enthusiast, our platform offers something for everyone. Join our\r\n");
      out.write("                            vibrant community of learners today and take the first step towards a successful tech\r\n");
      out.write("                            career! make it spell correct</div>\r\n");
      out.write("                        <p style=\"color: #ffa200; animation: zoomInOut 0.5s infinite alternate;\">All The Best !</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"feedbackModel\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal about -->\r\n");
      out.write("            <div class=\"site-content\" style=\"position: fixed; left: 10%\">\r\n");
      out.write("                <div style=\"padding: 20px; border-radius: 10px\">\r\n");
      out.write("                	 <span style=\"color: black\" onclick=\"closeModal('feedbackModel')\" class=\"close\">&times;</span>\r\n");
      out.write("                	 <h2>Student's Feedbacks</h2>\r\n");
      out.write("                     <div class=\"student-details\">  \r\n");
      out.write("				        	<table>\r\n");
      out.write("				        		<tr>\r\n");
      out.write("				        			<th>Sr No.</th>\r\n");
      out.write("				        			<th>Name</th>\r\n");
      out.write("				        			<th>Rating</th>\r\n");
      out.write("				        			<th>Comment</th>\r\n");
      out.write("				        			<th>Suggestion</th>\r\n");
      out.write("				        			<th>Date</th>\r\n");
      out.write("				        		</tr> \r\n");
      out.write("				                 \r\n");
      out.write("				        		");
  
						            SessionFactory factory = new Configuration().configure().buildSessionFactory();
						            Session studentSession = factory.openSession();
						            Transaction transaction = null;
						            
						            try {
						                transaction = studentSession.beginTransaction();
						                
						                Query<Feedback> query = studentSession.createQuery("FROM Feedback", Feedback.class);
						                List<Feedback> Feedbacks = query.getResultList();
						
						                for (int i = 0; i < Feedbacks.size(); i++) {
						                	Feedback feedback = Feedbacks.get(i);
						        
      out.write("\r\n");
      out.write("									        <tr style=\"background-color: #002233; height: 8px\"></tr>\r\n");
      out.write("									        <tr>\r\n");
      out.write("									            <td>");
      out.print( i + 1 );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( feedback.getStudentName() );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( feedback.getRating() );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( feedback.getComment() );
      out.write("</td>\r\n");
      out.write("									            <td>");
      out.print( feedback.getSuggession() );
      out.write("</td> \r\n");
      out.write("									            <td>");
      out.print( feedback.getDate() );
      out.write("</td> \r\n");
      out.write("									        </tr> \r\n");
      out.write("						        ");
 
						                }
						                transaction.commit();
						            } 
						            catch (Exception e) { 
						                if (transaction != null) {
						                    transaction.rollback();
						                }
						                e.printStackTrace();
						            } 
						            finally {
						                studentSession.close();
						                factory.close();
						            }
						        
      out.write("\r\n");
      out.write("				        	</table> \r\n");
      out.write("				    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"loginModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal Login -->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <span style=\"color: black\" onclick=\"closeModal('loginModal')\" class=\"close\">&times;</span>\r\n");
      out.write("                <h2 style=\"text-align: center; color: black\">Sign In</h2>\r\n");
      out.write("                <form id=\"login-user\" action=\"StudentLogin\" method=\"post\">\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input id=\"loginEmail\" type=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/lock.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input id=\"loginPass\" type=\"password\" name=\"password\" placeholder=\"Password\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"display: flex; margin-left: 35px\">\r\n");
      out.write("                        <div class=\"login-container\">\r\n");
      out.write("						  <input type=\"button\" class=\"login\" value=\"Sign In\" id=\"signInButton\" onclick=\"loginClicked('loginModal')\" style=\"background-color: #ffa200\">\r\n");
      out.write("						  <div class=\"progress-bar hidden\" id=\"progressBar\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("                        <a class=\"clickLogin\" style=\"font-size: small;\" onclick=\"openForgot()\">Forgot Password ?</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <p style=\"text-align: center; color: black;\">If not registered | <a onclick=\"closeAndOpen()\"\r\n");
      out.write("                            class=\"clickLogin\">Sign Up</a> </p>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"forgotPassword\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal Login -->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <span style=\"color: black\" onclick=\"closeModal('forgotPassword')\" class=\"close\">&times;</span>\r\n");
      out.write("                <h2 style=\"text-align: center; color: black\">Forgot Password</h2>\r\n");
      out.write("                <form id=\"forgot-password\" action=\"ForgotPassword\" method=\"post\">\r\n");
      out.write("                	<p style=\"margin: 10px\">Enter your registered email :</p>\r\n");
      out.write("                	<div style=\"display: flex;\">\r\n");
      out.write("                		<img src=\"./media/email.png\" style=\"width: 20px; height: 20px; margin-right: 10px; margin-top: 7px;\">\r\n");
      out.write("                		<input id=\"forgotEmail\" type=\"email\" name=\"email\" placeholder=\"Email ID\" required><br>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<hr>\r\n");
      out.write("                    <div class=\"login-container\">\r\n");
      out.write("						  <input type=\"button\" class=\"login\" value=\"Get Credentials\" id=\"getCredential\" onclick=\"getCredentialClicked('forgotPassword')\" style=\"margin-top: 10px; background-color: #ffa200\">\r\n");
      out.write("						  <div class=\"progress-bar hidden\" id=\"forgotProgress\"></div>\r\n");
      out.write("					</div> \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"pre-footer\">\r\n");
      out.write("            <p style=\"color: #fff; font-size: 15px; letter-spacing: 1px;\">Start your journey towards mastering the latest technologies !</p>\r\n");
      out.write("            <button onClick=\"openModal('registrationModal')\">Get Started<img src=\"./media/play.png\"\r\n");
      out.write("                        style=\"margin-left: 10px; width: 15px; height: 15px\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <footer style=\"background-color: #002233; display: flex; justify-content: space-between; margin: 0px 50px; color: #ffa200;\">\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>About Us</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<p>Technolearn Trainings is one of the best training institutes in Sinhagad Road/Anand Nagar, Pune. We provide professional courses for students, working professionals, job seekers and corporate employees with placement assurance.</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Features</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<a onclick=\"openModal('loginModal')\">Technology Roadmaps</a><p></p>\r\n");
      out.write("	                <a onclick=\"openModal('loginModal')\">Video Lectures</a><p></p>\r\n");
      out.write("	                <a onclick=\"openModal('loginModal')\">Coding Enhancement</a><p></p>\r\n");
      out.write("	                <a onclick=\"openModal('loginModal')\">Technical Quiz</a><p></p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Contact </h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<div style=\"margin-top: 20px;\">\r\n");
      out.write("                    <img src=\"./media/pin.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("                    <span id=\"tick-text\">Technolearn Trainings 133, Peshwa, 2nd Floor, Office No. 09, Near Chaitanya Hospital, Next to Parvati Bridge, Sinhgad Road, Parvati, Pune - 411030.</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/phone.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">91 88570 96492</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/email (1).png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">Info.technolearn@gmail.com</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Follow Us</h4>\r\n");
      out.write("        		<div class=\"footer-social-media\">\r\n");
      out.write("        			<a href=\"#\"><img src=\"./media/twitter.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/facebook.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/linkedin.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/instagram.png\"></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("            function openAndClose() {\r\n");
      out.write("                openModal('loginModal');\r\n");
      out.write("                closeModal('registrationModal');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function closeAndOpen() {\r\n");
      out.write("                openModal('registrationModal');\r\n");
      out.write("                closeModal('loginModal');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function openModal(modalId) {\r\n");
      out.write("                var modal = document.getElementById(modalId);\r\n");
      out.write("                modal.style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function closeModal(modalId) {\r\n");
      out.write("                var modal = document.getElementById(modalId);\r\n");
      out.write("                modal.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function openForgot(){\r\n");
      out.write("            	openModal('forgotPassword');\r\n");
      out.write("                closeModal('loginModal');\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function getCredentialClicked(modalId) {\r\n");
      out.write("	        	var forgotEmail = document.getElementById(\"forgotEmail\"); \r\n");
      out.write("	        	\r\n");
      out.write("	        	 if (forgotEmail.value.trim().length === 0) {\r\n");
      out.write("	        		 forgotEmail.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	        	 else {\r\n");
      out.write("	        		 forgotEmail.style.border = \"\";  \r\n");
      out.write("			     }\r\n");
      out.write("	        	 document.getElementById(\"getCredential\").style.display = \"none\"; \r\n");
      out.write("		            document.getElementById(\"forgotProgress\").classList.remove(\"hidden\"); \r\n");
      out.write("		            setTimeout(function() { \r\n");
      out.write("		            	document.getElementById(\"forgot-password\").submit();\r\n");
      out.write("		            }, 1000); \r\n");
      out.write("		            setTimeout(function() {  \r\n");
      out.write("		            	document.getElementById(\"getCredential\").style.display = \"block\"; \r\n");
      out.write("			            document.getElementById(\"forgotProgress\").classList.add(\"hidden\");\r\n");
      out.write("			            closeModal(modalId);\r\n");
      out.write("		            }, 10000); \r\n");
      out.write("	        }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("	        function loginClicked(modalId) { \r\n");
      out.write("	        	var loginEmail = document.getElementById(\"loginEmail\");\r\n");
      out.write("	        	var loginPass = document.getElementById(\"loginPass\");\r\n");
      out.write("	        	\r\n");
      out.write("	        	 if (loginEmail.value.trim().length === 0) {\r\n");
      out.write("	                 loginEmail.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	        	 else {\r\n");
      out.write("	        		 loginEmail.style.border = \"\";  \r\n");
      out.write("			     }\r\n");
      out.write("	             if (loginPass.value.trim().length === 0) {\r\n");
      out.write("	                 loginPass.style.border = \"1px solid red\";\r\n");
      out.write("	                 return;\r\n");
      out.write("	             }\r\n");
      out.write("	             else {\r\n");
      out.write("	            	 loginPass.style.border = \"\"; \r\n");
      out.write("			     }\r\n");
      out.write("	            document.getElementById(\"signInButton\").style.display = \"none\"; \r\n");
      out.write("	            document.getElementById(\"progressBar\").classList.remove(\"hidden\"); \r\n");
      out.write("	            setTimeout(function() { \r\n");
      out.write("	            	document.getElementById(\"login-user\").submit(); \r\n");
      out.write("	            }, 1500);  \r\n");
      out.write("	            setTimeout(function() {  \r\n");
      out.write("	            	document.getElementById(\"signInButton\").style.display = \"block\"; \r\n");
      out.write("		            document.getElementById(\"progressBar\").classList.add(\"hidden\");\r\n");
      out.write("		            closeModal(modalId);\r\n");
      out.write("	            }, 10000);  \r\n");
      out.write("	        }\r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("	        function registerClicked(modalId) { \r\n");
      out.write("	        	if (validateForm()) {\r\n");
      out.write("	        		document.getElementById(\"signUpButton\").style.display = \"none\"; \r\n");
      out.write("		            document.getElementById(\"proBar\").classList.remove(\"hidden\");\r\n");
      out.write("		            setTimeout(function() {\r\n");
      out.write("		            	document.getElementById(\"register-user\").submit(); \r\n");
      out.write("		            }, 500); \r\n");
      out.write("		        } \r\n");
      out.write("	        }\r\n");
      out.write("         \r\n");
      out.write("		    function validateForm() {\r\n");
      out.write("		        var firstName = document.getElementById(\"firstName\");\r\n");
      out.write("		        var lastName = document.getElementById(\"lastName\");\r\n");
      out.write("		        var email = document.getElementById(\"email\");\r\n");
      out.write("		        var number = document.getElementById(\"number\");\r\n");
      out.write("		        var password = document.getElementById(\"password\");\r\n");
      out.write("		        var confirmPassword = document.getElementById(\"confirmPassword\");\r\n");
      out.write("		\r\n");
      out.write("		        var valid = true;\r\n");
      out.write("		 \r\n");
      out.write("		        var nameRegex = /^[a-zA-Z]+$/;  \r\n");
      out.write("		        var emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("		        var passwordRegex = /^(?=.*[A-Z])(?=.*\\d).{6,}$/;  \r\n");
      out.write("		        var mobileRegex = /^[6-9]\\d{9}$/;  \r\n");
      out.write("		        \r\n");
      out.write("		        var error = document.getElementById(\"error\");\r\n");
      out.write("		        error.innerHTML = \"\"; \r\n");
      out.write("		\r\n");
      out.write("		      \r\n");
      out.write("		        if (!nameRegex.test(firstName.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid first name (only letters).\";\r\n");
      out.write("		            firstName.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid; \r\n");
      out.write("		        } else {\r\n");
      out.write("		            firstName.style.border = \"\"; \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        if (!nameRegex.test(lastName.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid last name (only letters).\";\r\n");
      out.write("		            lastName.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            lastName.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        if (!emailRegex.test(email.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid email address.\";\r\n");
      out.write("		            email.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            email.style.border = \"\"; \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (!mobileRegex.test(number.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Please enter a valid 10-digit mobile number starting with 6, 7, 8, or 9.\";\r\n");
      out.write("		            number.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            number.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (!passwordRegex.test(password.value.trim())) {\r\n");
      out.write("		            error.innerHTML = \"Password must be at least 6 characters long, have at least one uppercase letter, and one number.\";\r\n");
      out.write("		            password.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid;  \r\n");
      out.write("		        } else {\r\n");
      out.write("		            password.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        if (confirmPassword.value.trim() !== password.value.trim()) {\r\n");
      out.write("		            error.innerHTML = \"Confirm Password and Passwords do not match.\";\r\n");
      out.write("		            confirmPassword.style.border = \"1px solid red\";\r\n");
      out.write("		            valid = false;\r\n");
      out.write("		            return valid; \r\n");
      out.write("		        } else {\r\n");
      out.write("		            confirmPassword.style.border = \"\";  \r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        return valid;\r\n");
      out.write("		    }\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<script type=\"text/javascript\"> \r\n");
      out.write("		var mybutton = document.getElementById(\"scrollBtn\"); \r\n");
      out.write("		window.onscroll = function() {scrollFunction()};\r\n");
      out.write("\r\n");
      out.write("		function scrollFunction() {\r\n");
      out.write("		  if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {\r\n");
      out.write("		    mybutton.style.display = \"block\";\r\n");
      out.write("		  } else {\r\n");
      out.write("		    mybutton.style.display = \"none\";\r\n");
      out.write("		  }\r\n");
      out.write("		} \r\n");
      out.write("		function scrollToTop() { \r\n");
      out.write("		  document.documentElement.scrollTop = 0; \r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
