/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2024-05-11 04:41:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import techcraft.model.Roadmaps;
import techcraft.model.RoadmapSubTopics;
import java.util.List;

public final class Roadmap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("techcraft.model.Roadmaps");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("org.hibernate.cfg.Configuration");
    _jspx_imports_classes.add("techcraft.model.RoadmapSubTopics");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>TechCraft Learning Hub</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\"> \r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    	.dashboard-heading {\r\n");
      out.write("			margin: 10px 20px;\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.dashboard-heading span {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.about {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			flex-direction: column;\r\n");
      out.write("			flex: 1;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main {\r\n");
      out.write("			width: auto;\r\n");
      out.write("		    height: auto;\r\n");
      out.write("		    background-size: cover; \r\n");
      out.write("		    border: 3px solid #000;\r\n");
      out.write("		    border-radius: 20px; \r\n");
      out.write("		    background-image: url(\"./media/techback.jpg\");\r\n");
      out.write("		    margin: 0px 20px;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-main h2 {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			animation: zoomInOut 0.5s infinite alternate;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes zoomInOut {\r\n");
      out.write("		    0% {\r\n");
      out.write("		        transform: scale(1);\r\n");
      out.write("		    }\r\n");
      out.write("		    100% {\r\n");
      out.write("		        transform: scale(1.1);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		.roadmap-main p {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			margin: 0px 100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		fieldset {\r\n");
      out.write("			letter-spacing: 1px;\r\n");
      out.write("			margin: 30px 50px;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			border: solid 4px #00bfff;\r\n");
      out.write("			border-radius: 20px;\r\n");
      out.write("			height: auto;\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			margin-bottom: 50px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap {\r\n");
      out.write("			display: flex; \r\n");
      out.write("			justify-content: space-between; \r\n");
      out.write("			align-items: center; \r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap-subtopic {\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.upskill { \r\n");
      out.write("			width: 300px;\r\n");
      out.write("			border: solid 4px #000; \r\n");
      out.write("			border-radius: 10px; \r\n");
      out.write("			padding: 20px 50px;\r\n");
      out.write("			font-weight: normal;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.roadmap button {\r\n");
      out.write("			color: #fff;\r\n");
      out.write("		    cursor: pointer;  \r\n");
      out.write("		    letter-spacing: 1px;\r\n");
      out.write("		    background-color: #00334d; \r\n");
      out.write("		    padding: 12px 50px; \r\n");
      out.write("		    border-radius: 10px;\r\n");
      out.write("		    border: none;\r\n");
      out.write("		    font-size: 12px; \r\n");
      out.write("		    transition: transform 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.roadmap button:hover {\r\n");
      out.write("			background-color: #0bbfff;\r\n");
      out.write("			transform: scale(1.1);\r\n");
      out.write("		} \r\n");
      out.write("		\r\n");
      out.write("		.close {\r\n");
      out.write("			color: black;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("	    	font-size: 25px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		.modal-content a {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			color: #00bfff;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    	");

	        String name = (String) session.getAttribute("name");
	        if (name == null) {
	            response.sendRedirect("index.jsp");
	        } else {
	    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"./media/code-simple.png\" width=30px height=30px style=\"margin-left: 20px\">\r\n");
      out.write("            <h1>TechCraft</h1>\r\n");
      out.write("            <div class=\"vl\"></div>\r\n");
      out.write("            <div class=\"heading\">\r\n");
      out.write("                <a href=\"studentHome.jsp\" style=\"border-bottom: 2px solid #ffa200; margin-top: 10px; padding-bottom: 10px;\">Technology Roadmaps</a>\r\n");
      out.write("                <a href=\"videoLecture.jsp\" style=\"margin-top: 10px; color: #fff\">Video Lectures</a>\r\n");
      out.write("                <a href=\"codingInhancement.jsp\" style=\"margin-top: 10px; color: #fff\">Coding Enhancement</a>\r\n");
      out.write("                <a href=\"technicalQuiz.jsp\" style=\"margin-top: 10px; color: #fff\">Technical Quiz</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span style=\"flex: 1; margin-right: 0px;\"></span>\r\n");
      out.write("            <img src=\"./media/user.png\" width=20px height=20px style=\"margin-right: 15px\">\r\n");
      out.write("            <div class=\"popup\">\r\n");
      out.write("			  <label for=\"user\" class=\"userName\">");
      out.print( name );
      out.write("<img class=\"dropdown-icon\" alt=\"\" src=\"./media/play.png\"></label>    \r\n");
      out.write("			  <div class=\"popup-content\">\r\n");
      out.write("			    <a href=\"studentProfile.jsp\">Profile</a>\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"assessment.jsp\">Assessment</a> \r\n");
      out.write("			    <!-- <p></p>\r\n");
      out.write("			    <a href=\"Placement.jsp\">Placement</a>-->\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"Feedback.jsp\">Feedback</a>\r\n");
      out.write("			    <p></p>\r\n");
      out.write("			    <a href=\"#\" onclick=\"openModal('logoutModal')\">Logout</a>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div style=\"width: 100%; height: 100px;\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard-heading\">\r\n");
      out.write("        	<span style=\"font-size: 15px; color: #888888\">Dashboard:</span>\r\n");
      out.write("        	<span style=\"color: white\"> Technology Roadmaps</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"roadmap-main\">\r\n");
      out.write("        	<div class=\"roadmap-heading\"> <br>\r\n");
      out.write("        		<p>Technical Roadmap is a community effort to create roadmaps, guides and other educational content to help guide developers in picking up a path and guide their learnings.</p> \r\n");
      out.write("        		<fieldset>\r\n");
      out.write("		            ");
 String buttonValue = request.getParameter("submitButton"); 
      out.write("\r\n");
      out.write("			        <h1>");
      out.print(buttonValue );
      out.write(" Roadmap</h1>\r\n");
      out.write("			        \r\n");
      out.write("			        ");
 
				        SessionFactory factory = new Configuration().configure().buildSessionFactory();
			            Session studentSession = factory.openSession();
			            Transaction transaction = null; 
			            
			            try {
			                transaction = studentSession.beginTransaction();
			                
			                Query<Roadmaps> query = studentSession.createQuery("FROM Roadmaps WHERE technology= :technology", Roadmaps.class);
			                query.setParameter("technology", buttonValue);
			                List<Roadmaps> topics = query.getResultList();
			
			                for (int k = 0; k < topics.size(); k++) {
			                	Roadmaps roadmaps = topics.get(k);
			                	
			                	Query<RoadmapSubTopics> query1 = studentSession.createQuery("FROM RoadmapSubTopics WHERE topic= :topic", RoadmapSubTopics.class);
				                query1.setParameter("topic", roadmaps.getTopic());
				                List<RoadmapSubTopics> subTopics = query1.getResultList();
			                	
			                	if(k%2 == 0) {
			        
      out.write("\r\n");
      out.write("			        \r\n");
      out.write("							        <div class=\"roadmap\"> \r\n");
      out.write("							        	<span style=\"flex: 1;\"></span>\r\n");
      out.write("								        <div class=\"roadmap-subtopic\">\r\n");
      out.write("								        	 	<div style=\"display: flex;\">\r\n");
      out.write("								             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("								             		<div style=\"height: 30px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("								             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("								             	</div>\r\n");
      out.write("								             	<button style=\"background-color: #ffa200; cursor: default;transform: scale(1);\">");
      out.print(roadmaps.getTopic() );
      out.write("</button>\r\n");
      out.write("								             	<div style=\"display: flex;\">\r\n");
      out.write("									             	<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             	<div style=\"height: 10px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("									             	<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             </div>\r\n");
      out.write("								             	\r\n");
      out.write("								             ");
 for(int i=0; i<subTopics.size(); i++) {
								            		RoadmapSubTopics roadmapSubTopics = subTopics.get(i);  
								             
      out.write(" \r\n");
      out.write("								            	 	<button onclick=\"openSidebar('resource', '");
      out.print( roadmapSubTopics.getSubTopic() );
      out.write("', '");
      out.print( roadmapSubTopics.getDescription() );
      out.write("', '");
      out.print( roadmapSubTopics.getResource() );
      out.write("')\">");
      out.print( roadmapSubTopics.getSubTopic() );
      out.write("</button>\r\n");
      out.write("								              \r\n");
      out.write("									             	<div style=\"display: flex;\">\r\n");
      out.write("									             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             		<div style=\"height: 10px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("									             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             	</div>\r\n");
      out.write("								             ");
 
								             	}
								             
      out.write("\r\n");
      out.write("								        </div> \r\n");
      out.write("								        <span style=\"width: 100px;\"></span>\r\n");
      out.write("								        <div class=\"upskill\">Step by step guide to up skill in<br> ");
      out.print(roadmaps.getTopic() );
      out.write(" <br><br><b>");
      out.print(roadmaps.getDuration() );
      out.write("</b></div>\r\n");
      out.write("								        <span style=\"flex: 1;\"></span>\r\n");
      out.write("							        </div>\r\n");
      out.write("							        \r\n");
      out.write("							        <div style=\"display: flex;\">\r\n");
      out.write("							             <span style=\"flex: 1;\"></span> \r\n");
      out.write("							             <div style=\"width: 508px; border-top: solid 8px #00bfff; border-right: solid 8px #00bfff;\"></div>\r\n");
      out.write("							             <span style=\"flex: 1;\"></span>\r\n");
      out.write("							        </div>\r\n");
      out.write("							        \r\n");
      out.write("					");

			                	}else {
					
      out.write("\r\n");
      out.write("							        \r\n");
      out.write("							        <div class=\"roadmap\">\r\n");
      out.write("							        	<span style=\"flex: 1;\"></span>\r\n");
      out.write("								        <div class=\"upskill\">Step by step guide to up skill in<br> ");
      out.print(roadmaps.getTopic() );
      out.write(" <br><br><b>");
      out.print(roadmaps.getDuration() );
      out.write("</b></div>\r\n");
      out.write("								        <span style=\"width: 100px;\"></span>\r\n");
      out.write("								        <div class=\"roadmap-subtopic\">\r\n");
      out.write("								        	 	<div style=\"display: flex;\">\r\n");
      out.write("								             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("								             		<div style=\"height: 30px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("								             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("								             	</div>\r\n");
      out.write("								             	<button style=\"background-color: #ffa200; cursor: default;transform: scale(1);\">");
      out.print(roadmaps.getTopic() );
      out.write("</button>\r\n");
      out.write("								             	<div style=\"display: flex;\">\r\n");
      out.write("									             	<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             	<div style=\"height: 10px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("									             	<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             </div>\r\n");
      out.write("								             	\r\n");
      out.write("								             ");
 for(int i=0; i<subTopics.size(); i++) {
								            		RoadmapSubTopics roadmapSubTopics = subTopics.get(i);  
								             
      out.write(" \r\n");
      out.write("								            	 	<button onclick=\"openSidebar('resource', '");
      out.print( roadmapSubTopics.getSubTopic() );
      out.write("', '");
      out.print( roadmapSubTopics.getDescription() );
      out.write("', '");
      out.print( roadmapSubTopics.getResource() );
      out.write("')\">");
      out.print( roadmapSubTopics.getSubTopic() );
      out.write("</button>\r\n");
      out.write("								              \r\n");
      out.write("									             	<div style=\"display: flex;\">\r\n");
      out.write("									             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             		<div style=\"height: 10px; width: 0px; border: solid 4px #00bfff;\"></div>\r\n");
      out.write("									             		<span style=\"flex: 1;\"></span>\r\n");
      out.write("									             	</div>\r\n");
      out.write("								             ");
 
								             	}
								             
      out.write("\r\n");
      out.write("								        </div>\r\n");
      out.write("								        <span style=\"flex: 1;\"></span>\r\n");
      out.write("							        </div>\r\n");
      out.write("							        \r\n");
      out.write("							        <div style=\"display: flex;\">\r\n");
      out.write("							             <span style=\"flex: 1;\"></span> \r\n");
      out.write("							             <div style=\"width: 508px; border-top: solid 8px #00bfff; border-left: solid 8px #00bfff;\"></div>\r\n");
      out.write("							             <span style=\"flex: 1;\"></span>\r\n");
      out.write("							        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        ");
 
			                	}
			                }
			                transaction.commit();
			            } 
			            catch (Exception e) { 
			                if (transaction != null) {
			                    transaction.rollback();
			                }
			                e.printStackTrace();
			            }
			            finally {
			                studentSession.close();
			                factory.close();
			            }
			        
      out.write("\r\n");
      out.write("		   	        <br>continue learning ! <br><br><br>\r\n");
      out.write("		        </fieldset> \r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"resource\" class=\"modal-container\"> \r\n");
      out.write("		<!-- Modal content -->\r\n");
      out.write("			<div class=\"modal-content\" style=\"left: 85%; right: 0; height: 95vh; text-align: left; font-size: 13px;\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<span onclick=\"closeModal('resource')\" class=\"close\">&times;</span>\r\n");
      out.write("			<h3 id=\"topic\" style=\"text-align: left; color: black;\">hello</h3><hr><br>\r\n");
      out.write("			<span id=\"topic-description\" style=\"text-align: left; font-weight: normal;\">Angular is a popular open-source web application framework maintained by Google. It simplifies the development of dynamic single-page applications (SPAs) by providing a structured framework for building client-side applications. Understanding the basics of Angular, its core features, and architecture is essential for developing modern web applications.</span> \r\n");
      out.write("			<hr><br>\r\n");
      out.write("			<span style=\"text-align: left; font-weight: normal;\"><b>Visit the following resources to learn more:</b></span><br><br>\r\n");
      out.write("			<a id=\"video-link\" href=\"#\" target=\" \">Learn from Resource</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("         \r\n");
      out.write("        <div id=\"logoutModal\" class=\"modal-container\">\r\n");
      out.write("            <!-- Modal content -->\r\n");
      out.write("            <div class=\"modal-content\" style=\"max-width: 300px;\">\r\n");
      out.write("                <form id=\"logoutForm\" action=\"StudentLogout\">\r\n");
      out.write("                    <p style=\"color: black\">Are you sure, you want to Logout ?</p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px; align-items: center\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #ffa200; border: none\" value=\"Yes\"\r\n");
      out.write("                            onclick=\"logOut()\">\r\n");
      out.write("                        <input type=\"button\" class=\"login\" style=\"background-color: #d2d2e0; border: none\" value=\"Cancel\"\r\n");
      out.write("                            onclick=\"closeModal('logoutModal')\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <footer style=\"background-color: #002233; display: flex; justify-content: space-between; margin: 0px 50px; color: #ffa200;\">\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>About Us</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<p>Technolearn Trainings is one of the best training institutes in Sinhagad Road/Anand Nagar, Pune. We provide professional courses for students, working professionals, job seekers and corporate employees with placement assurance.</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Features</h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<a href=\"userHome.jsp\">Technology Roadmaps</a><p></p>\r\n");
      out.write("	                <a href=\"videoLecture.jsp\">Video Lectures</a><p></p>\r\n");
      out.write("	                <a href=\"codingInhancement.jsp\">Coding Enhancement</a><p></p>\r\n");
      out.write("	                <a href=\"technicalQuiz.jsp\">Technical Quiz</a><p></p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Contact </h4>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			<div style=\"margin-top: 20px;\">\r\n");
      out.write("                    <img src=\"./media/pin.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("                    <span id=\"tick-text\">Technolearn Trainings 133, Peshwa, 2nd Floor, Office No. 09, Near Chaitanya Hospital, Next to Parvati Bridge, Sinhgad Road, Parvati, Pune - 411030.</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/phone.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">91 88570 96492</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div style=\"margin-top: 20px;\">\r\n");
      out.write("	                    <img src=\"./media/email (1).png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("	                    <span id=\"tick-text\">Info.technolearn@gmail.com</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"footer-content\">\r\n");
      out.write("        		<h4>Follow Us</h4>\r\n");
      out.write("        		<div class=\"footer-social-media\">\r\n");
      out.write("        			<a href=\"#\"><img src=\"./media/twitter.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/facebook.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/linkedin.png\"></a>\r\n");
      out.write("                    <a href=\"#\"><img src=\"./media/instagram.png\"></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </footer>\r\n");
      out.write("		\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>&copy; 2024 TechCraft Learning Hub. @ Harshal Wandhare</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        <button onclick=\"scrollToTop()\" id=\"scrollBtn\" title=\"Go to top\"><img class=\"go-top\" alt=\"\" src=\"./media/play.png\"></button>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\"> \r\n");
      out.write("		var mybutton = document.getElementById(\"scrollBtn\"); \r\n");
      out.write("		window.onscroll = function() {scrollFunction()};\r\n");
      out.write("\r\n");
      out.write("		function scrollFunction() {\r\n");
      out.write("		  if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {\r\n");
      out.write("		    mybutton.style.display = \"block\";\r\n");
      out.write("		  } else {\r\n");
      out.write("		    mybutton.style.display = \"none\";\r\n");
      out.write("		  }\r\n");
      out.write("		} \r\n");
      out.write("		function scrollToTop() { \r\n");
      out.write("		  document.documentElement.scrollTop = 0; \r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function openModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	        }\r\n");
      out.write("	\r\n");
      out.write("	        function closeModal(modalId) {\r\n");
      out.write("	            var modal = document.getElementById(modalId);\r\n");
      out.write("	            modal.style.display = 'none';\r\n");
      out.write("	        }  \r\n");
      out.write("	        \r\n");
      out.write("	        function logOut() {\r\n");
      out.write("                document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("	        function openSidebar(modalId, topic, description, url) {\r\n");
      out.write("	        	\r\n");
      out.write("	            var modal = document.getElementById(modalId); \r\n");
      out.write("	            var headingElement = document.getElementById('topic');\r\n");
      out.write("	            var spanElement = document.getElementById('topic-description');\r\n");
      out.write("	            var linkElement = document.getElementById('video-link');\r\n");
      out.write("	\r\n");
      out.write("	            modal.style.display = 'block';\r\n");
      out.write("	            headingElement.innerText = topic; \r\n");
      out.write("	            \r\n");
      out.write("	            if(description == \"null\") {\r\n");
      out.write("	            	spanElement.innerText = \"In the context of a technology topic or a learning roadmap, a description typically refers to an explanatory text that provides an overview, details, or key points about the topic. This description aims to give the reader a clear understanding of what the topic is about, its significance, and possibly how it fits into the broader context of the technology or subject being studied. The description serves as a foundational piece of information that helps learners grasp the essence and significance of the topic before diving into more detailed content or practical exercises related to that topic.\";\r\n");
      out.write("	            }else {\r\n");
      out.write("	            	spanElement.innerText = description;\r\n");
      out.write("	            } \r\n");
      out.write("	            linkElement.href = 'https://www.youtube.com/watch?v=' + url;\r\n");
      out.write("	        }\r\n");
      out.write("		</script>\r\n");
      out.write("        \r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
